// ============================================================================
// PurePlate Indian FMCG Product Database
// 120+ real products with real ingredient lists from Indian market
// ============================================================================

export type ProductCategory =
  | "Instant Noodles"
  | "Chips & Snacks"
  | "Biscuits & Cookies"
  | "Beverages"
  | "Chocolates & Sweets"
  | "Dairy"
  | "Cooking Oil"
  | "Masala & Spices"
  | "Breakfast & Health"
  | "Sauces & Spreads"
  | "Atta & Staples"
  | "Ice Cream"
  | "Namkeen";

export interface IndianProduct {
  id: string;
  name: string;
  brand: string;
  category: ProductCategory;
  description: string;
  weight: string;
  isVeg: boolean;
  ingredients: string[];
  imageUrl: string | null;
}

// Brand color mapping for placeholder generation
export const BRAND_COLORS: Record<string, string> = {
  "Nestle": "#003DA5",
  "Maggi": "#E31837",
  "Lay's": "#FFD700",
  "PepsiCo": "#004B93",
  "ITC": "#003366",
  "Bingo": "#FF6600",
  "Kurkure": "#FF8C00",
  "Haldiram's": "#8B0000",
  "Parle": "#FFD700",
  "Britannia": "#1E3A5F",
  "Sunfeast": "#D4001A",
  "Cadbury": "#4B0082",
  "Mondelez": "#4B0082",
  "Oreo": "#000080",
  "Coca-Cola": "#E31837",
  "Pepsi": "#004B93",
  "Thums Up": "#E31837",
  "Amul": "#FFD700",
  "Mother Dairy": "#006400",
  "Dabur": "#006400",
  "Patanjali": "#FF8C00",
  "Fortune": "#003DA5",
  "Saffola": "#008000",
  "MDH": "#E31837",
  "Everest": "#E31837",
  "MTR": "#FFD700",
  "Kissan": "#E31837",
  "Kellogg's": "#E31837",
  "Quaker": "#003DA5",
  "Frooti": "#FFD700",
  "Paper Boat": "#006400",
  "Bournvita": "#4B0082",
  "Horlicks": "#FF8C00",
  "KitKat": "#E31837",
  "Uncle Chipps": "#FF6600",
  "Act II": "#E31837",
  "Bikano": "#8B0000",
  "Priya": "#E31837",
  "Aashirvaad": "#003366",
  "Maaza": "#FFD700",
  "Real": "#006400",
  "Tropicana": "#FF8C00",
  "Complan": "#003DA5",
  "Veeba": "#E31837",
  "Funfoods": "#FFD700",
  "Nandini": "#006400",
  "Kwality Wall's": "#003DA5",
  "Baskin Robbins": "#FF69B4",
  "Havmor": "#003DA5",
};

export const CATEGORY_EMOJIS: Record<ProductCategory, string> = {
  "Instant Noodles": "🍜",
  "Chips & Snacks": "🥔",
  "Biscuits & Cookies": "🍪",
  "Beverages": "🥤",
  "Chocolates & Sweets": "🍫",
  "Dairy": "🧈",
  "Cooking Oil": "🫒",
  "Masala & Spices": "🌶️",
  "Breakfast & Health": "🥣",
  "Sauces & Spreads": "🫙",
  "Atta & Staples": "🌾",
  "Ice Cream": "🍦",
  "Namkeen": "🥜",
};

export const INDIAN_PRODUCTS: IndianProduct[] = [
  // ======================== INSTANT NOODLES ========================
  {
    id: "maggi-masala-2min",
    name: "2-Minute Masala Noodles",
    brand: "Maggi",
    category: "Instant Noodles",
    description: "India's most popular instant noodles. The iconic yellow pack found in every Indian household.",
    weight: "70g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Palm Oil", "Iodised Salt", "Wheat Gluten", "Thickeners (508 & 412)", "Acidity Regulators (501(i) & 500(i))", "Humectant (451(i))", "Spices & Condiments", "Onion Powder", "Maltodextrin", "Sugar", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)", "Garlic Powder", "Turmeric", "Citric Acid"],
    imageUrl: null,
  },
  {
    id: "maggi-atta-noodles",
    name: "Atta Noodles",
    brand: "Maggi",
    category: "Instant Noodles",
    description: "Whole wheat variant of Maggi noodles marketed as a healthier alternative.",
    weight: "75g",
    isVeg: true,
    ingredients: ["Whole Wheat Flour (Atta) (84%)", "Palm Oil", "Iodised Salt", "Wheat Gluten", "Thickeners (INS 412)", "Acidity Regulator (INS 501(i))", "Humectant (INS 451(i))", "Spices", "Sugar", "Onion Powder", "Dehydrated Vegetables", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)"],
    imageUrl: null,
  },
  {
    id: "maggi-oats-noodles",
    name: "Oats Masala Noodles",
    brand: "Maggi",
    category: "Instant Noodles",
    description: "Noodles made with oats, marketed as a fiber-rich option.",
    weight: "73g",
    isVeg: true,
    ingredients: ["Oat Flour (45%)", "Refined Wheat Flour (Maida)", "Palm Oil", "Iodised Salt", "Wheat Gluten", "Thickeners (INS 412)", "Acidity Regulator (INS 501(i))", "Spices", "Maltodextrin", "Sugar", "Onion Powder", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)"],
    imageUrl: null,
  },
  {
    id: "maggi-chicken-noodles",
    name: "Chicken Noodles",
    brand: "Maggi",
    category: "Instant Noodles",
    description: "Non-vegetarian variant with chicken flavoring.",
    weight: "71g",
    isVeg: false,
    ingredients: ["Refined Wheat Flour (Maida)", "Palm Oil", "Iodised Salt", "Wheat Gluten", "Thickeners (INS 412)", "Chicken Fat Powder", "Dehydrated Chicken", "Spices", "Maltodextrin", "Sugar", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)", "Garlic Powder", "Onion Powder"],
    imageUrl: null,
  },
  {
    id: "maggi-veggie-masala",
    name: "Veggie Masala Noodles",
    brand: "Maggi",
    category: "Instant Noodles",
    description: "Noodles with real vegetable pieces in the tastemaker.",
    weight: "70g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Palm Oil", "Iodised Salt", "Dehydrated Vegetables (Carrot, Beans, Peas)", "Wheat Gluten", "Thickeners (508 & 412)", "Spices", "Maltodextrin", "Sugar", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)"],
    imageUrl: null,
  },
  {
    id: "yippee-noodles-magic",
    name: "Magic Masala Noodles",
    brand: "Sunfeast Yippee",
    category: "Instant Noodles",
    description: "ITC's rival to Maggi. Known for its round noodle cakes and non-sticky texture.",
    weight: "70g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Edible Vegetable Oil (Palm Oil)", "Iodised Salt", "Wheat Gluten", "Thickener (INS 412)", "Acidity Regulator (INS 501(i))", "Humectant (INS 451(i))", "Spices", "Dried Vegetables", "Maltodextrin", "Sugar", "Hydrolyzed Vegetable Protein", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)"],
    imageUrl: null,
  },
  {
    id: "top-ramen-curry",
    name: "Curry Noodles",
    brand: "Top Ramen",
    category: "Instant Noodles",
    description: "Classic Japanese-style instant noodles adapted for Indian taste with curry flavor.",
    weight: "70g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Edible Vegetable Oil (Palmolein)", "Iodised Salt", "Wheat Gluten", "Curry Powder", "Sugar", "Maltodextrin", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)", "Onion Powder", "Garlic Powder", "Acidity Regulator (INS 330)"],
    imageUrl: null,
  },
  {
    id: "chings-schezwan",
    name: "Schezwan Instant Noodles",
    brand: "Ching's Secret",
    category: "Instant Noodles",
    description: "Indo-Chinese flavor noodles with bold Schezwan spice profile.",
    weight: "60g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Edible Vegetable Oil (Palmolein)", "Salt", "Wheat Gluten", "Chilli Flakes", "Sichuan Pepper Extract", "Dried Vegetables", "Maltodextrin", "Sugar", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)", "Acidity Regulator (INS 330)", "INS 150c"],
    imageUrl: null,
  },
  {
    id: "patanjali-atta-noodles",
    name: "Atta Noodles",
    brand: "Patanjali",
    category: "Instant Noodles",
    description: "Patanjali's whole wheat noodles marketed as a desi, healthier alternative.",
    weight: "60g",
    isVeg: true,
    ingredients: ["Whole Wheat Flour (Atta)", "Edible Vegetable Oil (Rice Bran)", "Salt", "Spices", "Dehydrated Vegetables", "Sugar", "Turmeric", "Ajwain"],
    imageUrl: null,
  },
  {
    id: "knorr-soupy-noodles",
    name: "Soupy Noodles Mast Masala",
    brand: "Knorr",
    category: "Instant Noodles",
    description: "Hindustan Unilever's soupy noodles with extra broth.",
    weight: "75g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Palm Oil", "Corn Starch", "Iodised Salt", "Wheat Gluten", "Sugar", "Spices", "Maltodextrin", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)", "Dehydrated Vegetables", "Thickener (INS 412)"],
    imageUrl: null,
  },

  // ======================== CHIPS & SNACKS ========================
  {
    id: "lays-classic-salted",
    name: "Classic Salted Chips",
    brand: "Lay's",
    category: "Chips & Snacks",
    description: "The original salted potato chip. India's best-selling chip flavor.",
    weight: "52g",
    isVeg: true,
    ingredients: ["Potato", "Edible Vegetable Oil (Palmolein, Rice Bran Oil)", "Iodised Salt"],
    imageUrl: null,
  },
  {
    id: "lays-magic-masala",
    name: "Magic Masala Chips",
    brand: "Lay's",
    category: "Chips & Snacks",
    description: "India-exclusive masala flavor with tangy spice blend.",
    weight: "52g",
    isVeg: true,
    ingredients: ["Potato", "Edible Vegetable Oil (Palmolein, Rice Bran Oil)", "Seasoning (Maltodextrin, Sugar, Iodised Salt, Spices, Nature Identical Flavoring Substances, Acidity Regulators (INS 330, INS 296), Anti-caking Agent (INS 551))"],
    imageUrl: null,
  },
  {
    id: "lays-cream-onion",
    name: "Cream & Onion Chips",
    brand: "Lay's",
    category: "Chips & Snacks",
    description: "Creamy onion flavored potato chips.",
    weight: "52g",
    isVeg: true,
    ingredients: ["Potato", "Edible Vegetable Oil (Palmolein, Rice Bran Oil)", "Seasoning (Maltodextrin, Sugar, Iodised Salt, Onion Powder, Cream Cheese Powder, Spices, Milk Solids, Acidity Regulators (INS 330), Anti-caking Agent (INS 551))"],
    imageUrl: null,
  },
  {
    id: "lays-american-style",
    name: "American Style Cream & Onion",
    brand: "Lay's",
    category: "Chips & Snacks",
    description: "Thick-cut American-style chips with sour cream seasoning.",
    weight: "50g",
    isVeg: true,
    ingredients: ["Potato", "Edible Vegetable Oil (Palmolein)", "Seasoning (Maltodextrin, Iodised Salt, Cream Powder, Onion Powder, Sugar, Milk Solids, Spice Extract, Anti-caking Agent (INS 551), Acidity Regulator (INS 330))"],
    imageUrl: null,
  },
  {
    id: "bingo-mad-angles",
    name: "Mad Angles Achari Masti",
    brand: "Bingo",
    category: "Chips & Snacks",
    description: "ITC's triangle-shaped crispy snack with pickle flavor.",
    weight: "72.5g",
    isVeg: true,
    ingredients: ["Corn Flour", "Rice Flour", "Edible Vegetable Oil (Palmolein)", "Gram Flour", "Starch", "Iodised Salt", "Sugar", "Spices & Condiments", "Pickle Seasoning", "Maltodextrin", "Acidity Regulator (INS 330)", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)"],
    imageUrl: null,
  },
  {
    id: "bingo-original-style",
    name: "Original Style Chilli Sprinkled",
    brand: "Bingo",
    category: "Chips & Snacks",
    description: "Wavy potato chips with chilli seasoning from ITC.",
    weight: "66g",
    isVeg: true,
    ingredients: ["Potato", "Edible Vegetable Oil (Palmolein, Rice Bran Oil)", "Seasoning (Iodised Salt, Red Chilli Powder, Spices, Maltodextrin, Sugar, Anti-caking Agent (INS 551))"],
    imageUrl: null,
  },
  {
    id: "kurkure-masala-munch",
    name: "Masala Munch",
    brand: "Kurkure",
    category: "Chips & Snacks",
    description: "India's iconic crunchy puffed snack. Made with rice, corn, and gram dal.",
    weight: "90g",
    isVeg: true,
    ingredients: ["Rice Meal", "Edible Vegetable Oil (Palmolein)", "Corn Meal", "Gram Meal", "Seasoning (Spices & Condiments, Iodised Salt, Sugar, Maltodextrin, Tomato Powder)", "Acidity Regulator (INS 330)", "Anticaking Agent (INS 551)", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)"],
    imageUrl: null,
  },
  {
    id: "kurkure-chilli-chatka",
    name: "Green Chutney Rajasthani Style",
    brand: "Kurkure",
    category: "Chips & Snacks",
    description: "Kurkure variant with spicy green chutney flavor.",
    weight: "90g",
    isVeg: true,
    ingredients: ["Rice Meal", "Edible Vegetable Oil (Palmolein)", "Corn Meal", "Gram Meal", "Seasoning (Spices, Iodised Salt, Sugar, Maltodextrin, Coriander Powder, Mint Powder)", "Acidity Regulator (INS 330)", "Anticaking Agent (INS 551)", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)"],
    imageUrl: null,
  },
  {
    id: "uncle-chipps-spicy",
    name: "Spicy Treat",
    brand: "Uncle Chipps",
    category: "Chips & Snacks",
    description: "Classic Indian chip brand. The original desi chip before Lay's dominated.",
    weight: "55g",
    isVeg: true,
    ingredients: ["Potato", "Edible Vegetable Oil (Palmolein, Rice Bran Oil)", "Seasoning (Iodised Salt, Spices, Sugar, Maltodextrin, Tomato Powder, Anti-caking Agent (INS 551))"],
    imageUrl: null,
  },
  {
    id: "act2-classic-salted-popcorn",
    name: "Classic Salted Popcorn",
    brand: "Act II",
    category: "Chips & Snacks",
    description: "Microwave popcorn. India's leading popcorn brand.",
    weight: "99g",
    isVeg: true,
    ingredients: ["Corn Kernels", "Edible Vegetable Oil (Palmolein, Partially Hydrogenated Soyabean Oil)", "Iodised Salt", "Butter Flavor", "INS 319 (TBHQ)", "Color (INS 160c)"],
    imageUrl: null,
  },
  {
    id: "pringles-original",
    name: "Original Chips",
    brand: "Pringles",
    category: "Chips & Snacks",
    description: "Iconic stackable potato crisps in the cylinder tube.",
    weight: "107g",
    isVeg: true,
    ingredients: ["Dried Potatoes", "Vegetable Oil (Sunflower, Corn)", "Rice Flour", "Wheat Starch", "Maltodextrin", "Salt", "Emulsifier (INS 471)", "Dextrose"],
    imageUrl: null,
  },
  {
    id: "too-yumm-multigrain",
    name: "Multigrain Chips Dahi Papdi Chaat",
    brand: "Too Yumm!",
    category: "Chips & Snacks",
    description: "Baked multigrain chips marketed as a healthier alternative.",
    weight: "54g",
    isVeg: true,
    ingredients: ["Potato Flakes", "Rice Flour", "Corn Flour", "Edible Vegetable Oil (Rice Bran Oil)", "Ragi Flour", "Oat Flour", "Sesame Seeds", "Seasoning (Salt, Sugar, Spices, Dried Curd Powder, Maltodextrin, Chaat Masala)"],
    imageUrl: null,
  },

  // ======================== NAMKEEN ========================
  {
    id: "haldiram-aloo-bhujia",
    name: "Aloo Bhujia",
    brand: "Haldiram's",
    category: "Namkeen",
    description: "India's most popular namkeen. Crispy potato sev snack.",
    weight: "200g",
    isVeg: true,
    ingredients: ["Potatoes (44%)", "Edible Vegetable Oil (Cotton Seed, Corn & Palmolein Oil)", "Gram Pulse Flour", "Tepary Beans Flour", "Starch", "Iodised Salt", "Spices & Condiments", "Maltodextrin", "INS 319 (TBHQ)"],
    imageUrl: null,
  },
  {
    id: "haldiram-moong-dal",
    name: "Moong Dal",
    brand: "Haldiram's",
    category: "Namkeen",
    description: "Crispy fried moong dal namkeen with salt and spices.",
    weight: "200g",
    isVeg: true,
    ingredients: ["Moong Dal (60%)", "Edible Vegetable Oil (Palmolein, Cotton Seed Oil)", "Iodised Salt", "Black Pepper", "Asafoetida", "Red Chilli", "INS 319 (TBHQ)"],
    imageUrl: null,
  },
  {
    id: "haldiram-bhujia-sev",
    name: "Bhujia Sev",
    brand: "Haldiram's",
    category: "Namkeen",
    description: "Traditional Bikaneri bhujia. Thin crispy gram flour noodles.",
    weight: "200g",
    isVeg: true,
    ingredients: ["Gram Flour (Besan) (55%)", "Edible Vegetable Oil (Palmolein, Cotton Seed Oil)", "Moth Bean Flour", "Iodised Salt", "Spices", "Green Chilli", "INS 319 (TBHQ)"],
    imageUrl: null,
  },
  {
    id: "haldiram-navratan-mix",
    name: "Navratan Mix",
    brand: "Haldiram's",
    category: "Namkeen",
    description: "Premium mixed namkeen with 9 varieties of snacks.",
    weight: "200g",
    isVeg: true,
    ingredients: ["Gram Flour", "Edible Vegetable Oil (Palmolein)", "Peanuts", "Puffed Rice", "Potato Flakes", "Sugar", "Raisins", "Cashew Nuts", "Iodised Salt", "Spices", "Maltodextrin", "INS 319 (TBHQ)"],
    imageUrl: null,
  },
  {
    id: "bikano-bhujia",
    name: "Bikaji Bhujia",
    brand: "Bikano",
    category: "Namkeen",
    description: "Authentic Rajasthani bhujia sev from Bikaner.",
    weight: "200g",
    isVeg: true,
    ingredients: ["Gram Flour (Besan)", "Edible Vegetable Oil (Palmolein)", "Moth Bean Flour", "Iodised Salt", "Spices", "Red Chilli", "Turmeric", "INS 319 (TBHQ)"],
    imageUrl: null,
  },

  // ======================== BISCUITS & COOKIES ========================
  {
    id: "parle-g-original",
    name: "Parle-G Original Glucose Biscuit",
    brand: "Parle",
    category: "Biscuits & Cookies",
    description: "India's largest selling biscuit. The iconic glucose biscuit found in every home.",
    weight: "80g",
    isVeg: true,
    ingredients: ["Wheat Flour (Atta)", "Sugar", "Edible Vegetable Oil (Palm Oil)", "Invert Syrup", "Milk Solids", "Raising Agents (INS 503(ii), INS 500(ii))", "Iodised Salt", "Emulsifier (INS 322)", "Dough Conditioner (INS 223)"],
    imageUrl: null,
  },
  {
    id: "parle-marie",
    name: "Marie Biscuit",
    brand: "Parle",
    category: "Biscuits & Cookies",
    description: "Light and crispy Marie biscuit. Lower sugar than glucose biscuits.",
    weight: "65g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Sugar", "Edible Vegetable Oil (Palm Oil)", "Invert Syrup", "Milk Solids", "Iodised Salt", "Raising Agents (INS 503(ii), INS 500(ii))", "Emulsifier (INS 322)"],
    imageUrl: null,
  },
  {
    id: "parle-monaco",
    name: "Monaco Classic",
    brand: "Parle",
    category: "Biscuits & Cookies",
    description: "India's popular salty cracker biscuit. Perfect with chai.",
    weight: "75.4g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Edible Vegetable Oil (Palm Oil)", "Sugar", "Iodised Salt", "Corn Starch", "Invert Syrup", "Yeast", "Raising Agent (INS 500(ii))", "Emulsifier (INS 322)", "Dough Conditioner (INS 223)"],
    imageUrl: null,
  },
  {
    id: "britannia-good-day-butter",
    name: "Good Day Butter Cookies",
    brand: "Britannia",
    category: "Biscuits & Cookies",
    description: "Premium butter cookies with signature swirl shape.",
    weight: "75g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Sugar", "Edible Vegetable Fat (Palm Oil)", "Butter (8%)", "Invert Syrup", "Milk Solids", "Raising Agents (INS 503(ii), INS 500(ii))", "Iodised Salt", "Emulsifier (INS 322)", "Dough Conditioner (INS 223)", "Artificial Flavoring – Butter"],
    imageUrl: null,
  },
  {
    id: "britannia-marie-gold",
    name: "Marie Gold",
    brand: "Britannia",
    category: "Biscuits & Cookies",
    description: "Britannia's version of the Marie biscuit with added vitamins.",
    weight: "83g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Sugar", "Edible Vegetable Oil (Palm Oil)", "Invert Syrup", "Liquid Glucose", "Milk Solids", "Raising Agents (INS 503(ii), INS 500(ii))", "Iodised Salt", "Emulsifier (INS 322)", "Added Vitamins"],
    imageUrl: null,
  },
  {
    id: "britannia-bourbon",
    name: "Bourbon Chocolate Cream",
    brand: "Britannia",
    category: "Biscuits & Cookies",
    description: "Classic chocolate cream sandwich biscuit.",
    weight: "100g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Sugar", "Edible Vegetable Fat (Palm Oil, Palmolein)", "Cocoa Solids (6%)", "Invert Syrup", "Liquid Glucose", "Milk Solids", "Raising Agents (INS 503(ii), INS 500(ii))", "Emulsifier (INS 322)", "Iodised Salt", "Synthetic Colors", "Artificial Flavoring – Chocolate & Vanilla"],
    imageUrl: null,
  },
  {
    id: "sunfeast-dark-fantasy",
    name: "Dark Fantasy Choco Fills",
    brand: "Sunfeast",
    category: "Biscuits & Cookies",
    description: "Premium cookie with chocolate cream filling. ITC's bestselling biscuit.",
    weight: "75g",
    isVeg: true,
    ingredients: ["Choco Creme (38%) [Sugar, Refined Palmolein, Cocoa Solids, Milk Solids, Emulsifier (INS 322)]", "Refined Wheat Flour (Maida)", "Sugar", "Edible Vegetable Oil (Palmolein, Interesterified Fat)", "Hydrogenated Vegetable Oils", "Liquid Glucose", "Cocoa Solids", "Invert Syrup", "Milk Solids", "Raising Agents (INS 500(ii), INS 503(ii))", "Iodised Salt", "Emulsifier (INS 322)"],
    imageUrl: null,
  },
  {
    id: "oreo-vanilla",
    name: "Original Vanilla Creme Biscuit",
    brand: "Oreo",
    category: "Biscuits & Cookies",
    description: "America's favorite cookie, now India's too. Twist, lick, and dunk.",
    weight: "120g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Sugar", "Edible Vegetable Fat (Palm Oil, Interesterified Vegetable Fat)", "Invert Sugar Syrup", "Cocoa Solids (4.5%)", "Starch", "Leavening Agents (INS 500(ii), INS 503(ii))", "Iodised Salt", "Emulsifier (INS 322)", "Synthetic Food Color (INS 150d)"],
    imageUrl: null,
  },
  {
    id: "hide-seek-chocolate",
    name: "Hide & Seek Chocolate Chip",
    brand: "Parle",
    category: "Biscuits & Cookies",
    description: "Chocolate chip cookies. Competitor to Dark Fantasy.",
    weight: "100g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Sugar", "Edible Vegetable Oil (Palm Oil)", "Choco Chips (10%)", "Cocoa Solids", "Invert Syrup", "Liquid Glucose", "Milk Solids", "Raising Agents (INS 500(ii), INS 503(ii))", "Iodised Salt", "Emulsifier (INS 322)", "Artificial Flavoring"],
    imageUrl: null,
  },
  {
    id: "britannia-tiger-krunch",
    name: "Tiger Krunch Choco Biscuits",
    brand: "Britannia",
    category: "Biscuits & Cookies",
    description: "Kids-focused energy biscuit with chocolate.",
    weight: "72g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Sugar", "Edible Vegetable Oil (Palm Oil)", "Cocoa Solids", "Liquid Glucose", "Invert Syrup", "Milk Solids", "Raising Agents (INS 503(ii), INS 500(ii))", "Iodised Salt", "Emulsifier (INS 322)"],
    imageUrl: null,
  },
  {
    id: "sunfeast-mom-magic",
    name: "Mom's Magic Butter Cookies",
    brand: "Sunfeast",
    category: "Biscuits & Cookies",
    description: "Rich butter cookies from ITC with cashew pieces.",
    weight: "75g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Sugar", "Edible Vegetable Fat (Palmolein)", "Butter (5%)", "Cashew Nuts (3%)", "Invert Syrup", "Milk Solids", "Raising Agent (INS 500(ii))", "Iodised Salt", "Emulsifier (INS 322)", "Artificial Flavoring – Butter"],
    imageUrl: null,
  },
  {
    id: "britannia-50-50",
    name: "50-50 Maska Chaska",
    brand: "Britannia",
    category: "Biscuits & Cookies",
    description: "Sweet and salty cracker with butter flavor.",
    weight: "71g",
    isVeg: true,
    ingredients: ["Refined Wheat Flour (Maida)", "Edible Vegetable Oil (Palm Oil)", "Sugar", "Butter (3%)", "Iodised Salt", "Invert Syrup", "Seasoning (Maltodextrin, Salt, Spices)", "Raising Agent (INS 500(ii))", "Emulsifier (INS 322)"],
    imageUrl: null,
  },

  // ======================== BEVERAGES ========================
  {
    id: "coca-cola-original",
    name: "Coca-Cola Original",
    brand: "Coca-Cola",
    category: "Beverages",
    description: "The world's most recognized soft drink. India's carbonated market leader.",
    weight: "300ml",
    isVeg: true,
    ingredients: ["Carbonated Water", "Sugar", "INS 150d (Sulphite Ammonia Caramel)", "Acidity Regulator (INS 338)", "Natural Flavoring Substances", "Caffeine"],
    imageUrl: null,
  },
  {
    id: "thums-up",
    name: "Thums Up",
    brand: "Thums Up",
    category: "Beverages",
    description: "India's strongest cola. Originally Indian, now owned by Coca-Cola.",
    weight: "300ml",
    isVeg: true,
    ingredients: ["Carbonated Water", "Sugar", "INS 150d (Sulphite Ammonia Caramel)", "Acidity Regulator (INS 338)", "Natural Flavoring Substances Including Caffeine"],
    imageUrl: null,
  },
  {
    id: "pepsi-can",
    name: "Pepsi",
    brand: "Pepsi",
    category: "Beverages",
    description: "PepsiCo's flagship cola. Major rival to Coca-Cola in India.",
    weight: "300ml",
    isVeg: true,
    ingredients: ["Carbonated Water", "Sugar", "INS 150d (Sulphite Ammonia Caramel)", "Acidity Regulator (INS 338)", "Caffeine", "Natural Flavoring Substances"],
    imageUrl: null,
  },
  {
    id: "sprite-can",
    name: "Sprite",
    brand: "Coca-Cola",
    category: "Beverages",
    description: "Clear lemon-lime soda. Popular in India's hot climate.",
    weight: "300ml",
    isVeg: true,
    ingredients: ["Carbonated Water", "Sugar", "Acidity Regulator (INS 330)", "Natural Flavoring Substances"],
    imageUrl: null,
  },
  {
    id: "frooti-mango",
    name: "Frooti Mango Drink",
    brand: "Frooti",
    category: "Beverages",
    description: "India's iconic mango drink in the tetra pack. 'Mango Frooti, Fresh and Juicy.'",
    weight: "200ml",
    isVeg: true,
    ingredients: ["Water", "Sugar", "Mango Pulp (15%)", "Acidity Regulator (INS 330)", "Preservative (INS 211)", "Antioxidant (INS 300)", "Contains Added Flavors (Nature Identical)"],
    imageUrl: null,
  },
  {
    id: "maaza-mango",
    name: "Maaza Mango Drink",
    brand: "Maaza",
    category: "Beverages",
    description: "Coca-Cola's mango drink competing with Frooti/Slice.",
    weight: "250ml",
    isVeg: true,
    ingredients: ["Water", "Sugar", "Mango Pulp (14%)", "Acidity Regulator (INS 330)", "Antioxidant (INS 300)", "Stabilizers (INS 440, INS 412)", "Contains Added Flavors"],
    imageUrl: null,
  },
  {
    id: "real-mixed-fruit",
    name: "Mixed Fruit Juice",
    brand: "Real",
    category: "Beverages",
    description: "Dabur's fruit juice brand. Marketed as 'real fruit juice'.",
    weight: "200ml",
    isVeg: true,
    ingredients: ["Water", "Mixed Fruit Concentrate (Apple, Grape, Mango, Pineapple, Guava)", "Sugar", "Acidity Regulator (INS 330)", "Preservative (INS 211)", "Antioxidant (INS 300)", "Stabilizer (INS 440)", "Colors"],
    imageUrl: null,
  },
  {
    id: "paper-boat-aam-panna",
    name: "Aam Panna",
    brand: "Paper Boat",
    category: "Beverages",
    description: "Traditional Indian raw mango drink. Premium nostalgia brand.",
    weight: "250ml",
    isVeg: true,
    ingredients: ["Water", "Sugar", "Raw Mango Pulp (12%)", "Iodised Salt", "Cumin Powder", "Black Salt", "Mint Extract", "Acidity Regulator (INS 330)", "Preservative (INS 211)"],
    imageUrl: null,
  },
  {
    id: "tropicana-orange",
    name: "Orange Juice",
    brand: "Tropicana",
    category: "Beverages",
    description: "PepsiCo's premium juice brand. '100% juice' claim.",
    weight: "200ml",
    isVeg: true,
    ingredients: ["Orange Juice from Concentrate (Reconstituted)", "Water", "Sugar", "Acidity Regulator (INS 330)", "Preservative (INS 202)", "Antioxidant (INS 300)"],
    imageUrl: null,
  },
  {
    id: "bournvita-chocolate",
    name: "Cadbury Bournvita",
    brand: "Bournvita",
    category: "Beverages",
    description: "India's iconic chocolate health drink for children.",
    weight: "500g",
    isVeg: true,
    ingredients: ["Sugar", "Cocoa Solids (12%)", "Malt Extract", "Liquid Glucose", "Milk Solids", "Emulsifier (INS 322)", "Raising Agent (INS 500(ii))", "Added Vitamins & Minerals", "Artificial Flavoring – Chocolate & Caramel", "INS 150c"],
    imageUrl: null,
  },
  {
    id: "horlicks-classic",
    name: "Classic Malt Horlicks",
    brand: "Horlicks",
    category: "Beverages",
    description: "Malt-based health drink. 'Taller, Stronger, Sharper.'",
    weight: "500g",
    isVeg: true,
    ingredients: ["Wheat Flour", "Malted Barley (26%)", "Sugar", "Milk Solids", "Cocoa Powder", "Edible Vegetable Oil", "Minerals", "Vitamins", "Acidity Regulator (INS 500(ii))", "Salt", "Emulsifier (INS 322)", "Artificial Flavoring"],
    imageUrl: null,
  },
  {
    id: "complan-classic",
    name: "Complan Classic Chocolate",
    brand: "Complan",
    category: "Beverages",
    description: "Nutrition drink for children. Competing with Bournvita and Horlicks.",
    weight: "500g",
    isVeg: true,
    ingredients: ["Skimmed Milk Powder", "Maltodextrin", "Sugar", "Edible Vegetable Oil (Palmolein)", "Cocoa Solids", "Minerals", "Vitamins", "Soy Protein Isolate", "Emulsifier (INS 322)", "Acidity Regulator (INS 500(ii))", "Artificial Flavoring"],
    imageUrl: null,
  },
  {
    id: "limca",
    name: "Limca",
    brand: "Coca-Cola",
    category: "Beverages",
    description: "India-origin lemon-lime soda. Refreshing in hot weather.",
    weight: "300ml",
    isVeg: true,
    ingredients: ["Carbonated Water", "Sugar", "Acidity Regulator (INS 330)", "Natural Lemon-Lime Flavoring", "Stabilizer (INS 444)", "Antioxidant (INS 300)"],
    imageUrl: null,
  },
  {
    id: "mountain-dew",
    name: "Mountain Dew",
    brand: "PepsiCo",
    category: "Beverages",
    description: "High-caffeine citrus soda. 'Darr Ke Aage Jeet Hai.'",
    weight: "300ml",
    isVeg: true,
    ingredients: ["Carbonated Water", "Sugar", "Acidity Regulators (INS 330, INS 331(iii))", "Concentrated Orange Juice", "Caffeine", "Natural Flavoring Substances", "Antioxidant (INS 300)", "Stabilizer (INS 444)", "Color (INS 110)"],
    imageUrl: null,
  },

  // ======================== CHOCOLATES & SWEETS ========================
  {
    id: "cadbury-dairy-milk",
    name: "Dairy Milk Chocolate",
    brand: "Cadbury",
    category: "Chocolates & Sweets",
    description: "India's most loved chocolate. 'Kuch Meetha Ho Jaaye.'",
    weight: "49.5g",
    isVeg: true,
    ingredients: ["Sugar", "Cocoa Butter", "Milk Solids (20%)", "Cocoa Solids (Min 25%)", "Emulsifier (INS 442, INS 476)", "Vegetable Fat (Palm Oil)", "Nature Identical Flavoring – Vanilla"],
    imageUrl: null,
  },
  {
    id: "cadbury-silk",
    name: "Dairy Milk Silk",
    brand: "Cadbury",
    category: "Chocolates & Sweets",
    description: "Premium smoother version of Dairy Milk with extra cocoa butter.",
    weight: "60g",
    isVeg: true,
    ingredients: ["Sugar", "Cocoa Butter", "Milk Solids (20%)", "Cocoa Solids (Min 33%)", "Emulsifier (INS 442, INS 476)", "Vegetable Fat", "Nature Identical Flavoring – Vanilla"],
    imageUrl: null,
  },
  {
    id: "cadbury-5star",
    name: "5 Star Chocolate Bar",
    brand: "Cadbury",
    category: "Chocolates & Sweets",
    description: "Chocolate bar with caramel and nougat center.",
    weight: "40g",
    isVeg: true,
    ingredients: ["Sugar", "Glucose Syrup", "Vegetable Fat (Palm Oil)", "Milk Solids", "Cocoa Butter", "Cocoa Solids", "Hydrogenated Vegetable Fat", "Wheat Flour", "Maltodextrin", "Emulsifier (INS 322)", "Iodised Salt", "Artificial Flavoring – Vanilla & Caramel"],
    imageUrl: null,
  },
  {
    id: "kitkat-4-finger",
    name: "KitKat 4 Finger",
    brand: "KitKat",
    category: "Chocolates & Sweets",
    description: "'Have a break, have a KitKat.' Wafer fingers coated in chocolate.",
    weight: "37.3g",
    isVeg: true,
    ingredients: ["Sugar", "Refined Wheat Flour (Maida)", "Cocoa Butter", "Vegetable Fat (Palm Oil, Sal Fat)", "Cocoa Mass", "Milk Solids", "Whey Protein Concentrate", "Emulsifier (INS 322)", "Yeast", "Raising Agent (INS 500(ii))", "Iodised Salt", "Nature Identical Flavoring – Vanilla"],
    imageUrl: null,
  },
  {
    id: "nestle-munch",
    name: "Munch Crunch Bar",
    brand: "Nestle",
    category: "Chocolates & Sweets",
    description: "Crunchy wafer chocolate bar at ₹5. India's top-selling small chocolate.",
    weight: "23g",
    isVeg: true,
    ingredients: ["Sugar", "Refined Wheat Flour (Maida)", "Edible Vegetable Fat (Palm Oil, Palmolein)", "Cocoa Solids", "Milk Solids", "Liquid Glucose", "Emulsifier (INS 322)", "Iodised Salt", "Raising Agent (INS 500(ii))", "Artificial Flavoring"],
    imageUrl: null,
  },
  {
    id: "cadbury-gems",
    name: "Gems Chocolate",
    brand: "Cadbury",
    category: "Chocolates & Sweets",
    description: "Colorful sugar-coated chocolate buttons for kids.",
    weight: "17.8g",
    isVeg: true,
    ingredients: ["Sugar", "Cocoa Butter", "Milk Solids", "Cocoa Solids", "Emulsifier (INS 322)", "Vegetable Fat (Palm Oil)", "Glazing Agent (INS 903, INS 904)", "Permitted Synthetic Food Colors (INS 102, INS 110, INS 129, INS 133)", "Nature Identical Flavoring"],
    imageUrl: null,
  },
  {
    id: "cadbury-perk",
    name: "Perk Wafer Chocolate",
    brand: "Cadbury",
    category: "Chocolates & Sweets",
    description: "Light wafer chocolate. Budget-friendly option.",
    weight: "22g",
    isVeg: true,
    ingredients: ["Sugar", "Refined Wheat Flour (Maida)", "Cocoa Butter", "Edible Vegetable Fat (Palm Oil)", "Cocoa Solids", "Milk Solids", "Liquid Glucose", "Emulsifier (INS 322)", "Raising Agent (INS 500(ii))", "Iodised Salt", "Artificial Flavoring"],
    imageUrl: null,
  },
  {
    id: "ferrero-rocher",
    name: "Ferrero Rocher",
    brand: "Ferrero",
    category: "Chocolates & Sweets",
    description: "Premium Italian chocolate with hazelnut. Gift-giving favorite.",
    weight: "37.5g (3 pcs)",
    isVeg: true,
    ingredients: ["Milk Chocolate (Sugar, Cocoa Butter, Cocoa Mass, Skimmed Milk Powder, Whey, Emulsifier (INS 322))", "Hazelnuts (28.5%)", "Sugar", "Palm Oil", "Wheat Flour", "Whey Powder", "Skimmed Milk Powder", "Raising Agent (INS 500(ii))", "Vanillin"],
    imageUrl: null,
  },

  // ======================== DAIRY ========================
  {
    id: "amul-butter",
    name: "Amul Butter",
    brand: "Amul",
    category: "Dairy",
    description: "'Utterly Butterly Delicious.' India's most trusted butter brand.",
    weight: "100g",
    isVeg: true,
    ingredients: ["Pasteurized Cream (Milk Fat 80%)", "Common Salt (2.5%)", "Annatto Color (INS 160b)"],
    imageUrl: null,
  },
  {
    id: "amul-cheese-slices",
    name: "Amul Cheese Slices",
    brand: "Amul",
    category: "Dairy",
    description: "Processed cheese slices. India's most popular cheese brand.",
    weight: "100g",
    isVeg: true,
    ingredients: ["Cheese (51%)", "Water", "Emulsifying Salts (INS 339(ii), INS 452(i))", "Milk Solids", "Common Salt", "Preservative (INS 200)", "Acidity Regulator (INS 270)", "Permitted Natural Food Color (INS 160b)"],
    imageUrl: null,
  },
  {
    id: "amul-dark-chocolate",
    name: "Amul Dark Chocolate",
    brand: "Amul",
    category: "Chocolates & Sweets",
    description: "Affordable dark chocolate at a fraction of imported brands.",
    weight: "150g",
    isVeg: true,
    ingredients: ["Sugar", "Cocoa Butter", "Cocoa Mass (Min 55%)", "Milk Solids", "Emulsifier (INS 322)", "Nature Identical Flavoring – Vanilla"],
    imageUrl: null,
  },
  {
    id: "amul-taaza-milk",
    name: "Amul Taaza Toned Milk",
    brand: "Amul",
    category: "Dairy",
    description: "Toned milk with 3% fat. India's most consumed packaged milk.",
    weight: "500ml",
    isVeg: true,
    ingredients: ["Toned Milk (Fat: 3.0%, SNF: 8.5%)"],
    imageUrl: null,
  },
  {
    id: "mother-dairy-dahi",
    name: "Classic Dahi (Curd)",
    brand: "Mother Dairy",
    category: "Dairy",
    description: "Fresh curd made from toned milk. Delhi's household staple.",
    weight: "400g",
    isVeg: true,
    ingredients: ["Toned Milk", "Lactic Acid Culture"],
    imageUrl: null,
  },
  {
    id: "britannia-cheese-cubes",
    name: "Cheese Cubes",
    brand: "Britannia",
    category: "Dairy",
    description: "Processed cheese cubes popular for sandwiches and snacking.",
    weight: "200g",
    isVeg: true,
    ingredients: ["Cheese (51%)", "Water", "Emulsifying Salts (INS 339(ii), INS 452(i))", "Milk Solids", "Common Salt", "Preservative (INS 200)", "Acidity Regulator (INS 270)", "Permitted Natural Food Color (INS 160b)"],
    imageUrl: null,
  },

  // ======================== COOKING OIL ========================
  {
    id: "fortune-sunlite-oil",
    name: "Sunlite Refined Sunflower Oil",
    brand: "Fortune",
    category: "Cooking Oil",
    description: "India's leading refined sunflower cooking oil.",
    weight: "1L",
    isVeg: true,
    ingredients: ["Refined Sunflower Oil", "Antioxidant (INS 319 TBHQ)"],
    imageUrl: null,
  },
  {
    id: "saffola-gold",
    name: "Saffola Gold Blended Oil",
    brand: "Saffola",
    category: "Cooking Oil",
    description: "Blended cooking oil marketed as heart-healthy with dual seed technology.",
    weight: "1L",
    isVeg: true,
    ingredients: ["Rice Bran Oil (80%)", "Sunflower Oil (20%)", "Antioxidant (INS 319 TBHQ)"],
    imageUrl: null,
  },
  {
    id: "patanjali-mustard-oil",
    name: "Kachi Ghani Mustard Oil",
    brand: "Patanjali",
    category: "Cooking Oil",
    description: "Cold-pressed mustard oil. Traditional Indian cooking staple.",
    weight: "1L",
    isVeg: true,
    ingredients: ["Cold Pressed Mustard Oil"],
    imageUrl: null,
  },

  // ======================== MASALA & SPICES ========================
  {
    id: "mdh-chana-masala",
    name: "Chana Masala",
    brand: "MDH",
    category: "Masala & Spices",
    description: "India's most famous spice blend for chickpea curry.",
    weight: "100g",
    isVeg: true,
    ingredients: ["Coriander", "Red Chilli", "Salt", "Mango Powder (Amchur)", "Cumin", "Turmeric", "Black Pepper", "Fennel", "Bay Leaf", "Cinnamon", "Cloves", "Cassia", "Fenugreek Leaves", "Ginger Powder"],
    imageUrl: null,
  },
  {
    id: "mdh-garam-masala",
    name: "Garam Masala",
    brand: "MDH",
    category: "Masala & Spices",
    description: "Essential Indian spice blend used in almost every household.",
    weight: "100g",
    isVeg: true,
    ingredients: ["Coriander", "Cumin", "Black Pepper", "Cardamom", "Cinnamon", "Cloves", "Bay Leaf", "Fennel", "Mace", "Nutmeg"],
    imageUrl: null,
  },
  {
    id: "everest-kitchen-king",
    name: "Kitchen King Masala",
    brand: "Everest",
    category: "Masala & Spices",
    description: "All-purpose masala powder. Versatile spice for any vegetable dish.",
    weight: "100g",
    isVeg: true,
    ingredients: ["Coriander", "Red Chilli", "Turmeric", "Cumin", "Salt", "Fenugreek Leaves", "Mango Powder", "Fennel", "Black Pepper", "Cinnamon", "Cloves", "Cardamom", "Ginger", "Bay Leaf"],
    imageUrl: null,
  },
  {
    id: "everest-pav-bhaji",
    name: "Pav Bhaji Masala",
    brand: "Everest",
    category: "Masala & Spices",
    description: "Spice blend for Mumbai's iconic street food — Pav Bhaji.",
    weight: "100g",
    isVeg: true,
    ingredients: ["Coriander", "Red Chilli", "Cumin", "Salt", "Black Pepper", "Dried Mango", "Turmeric", "Fennel", "Cinnamon", "Cloves", "Cardamom", "Cassia"],
    imageUrl: null,
  },

  // ======================== SAUCES & SPREADS ========================
  {
    id: "kissan-tomato-ketchup",
    name: "Fresh Tomato Ketchup",
    brand: "Kissan",
    category: "Sauces & Spreads",
    description: "India's most popular ketchup. Found alongside every plate of Maggi.",
    weight: "500g",
    isVeg: true,
    ingredients: ["Tomato Paste (28%)", "Sugar", "Water", "Iodised Salt", "Acetic Acid (INS 260)", "Onion Powder", "Garlic Powder", "Spices", "Thickener (INS 415)", "Preservative (INS 211)", "Sequestrant (INS 385)"],
    imageUrl: null,
  },
  {
    id: "maggi-hot-sweet",
    name: "Hot & Sweet Tomato Chilli Sauce",
    brand: "Maggi",
    category: "Sauces & Spreads",
    description: "Nestle's tangy tomato sauce. 'It's Different.'",
    weight: "500g",
    isVeg: true,
    ingredients: ["Tomato Paste", "Sugar", "Water", "Iodised Salt", "Red Chilli", "Acetic Acid (INS 260)", "Modified Starch (INS 1422)", "Thickener (INS 415)", "Garlic Powder", "Preservative (INS 211)", "INS 150c"],
    imageUrl: null,
  },
  {
    id: "veeba-mayo",
    name: "Eggless Mayonnaise",
    brand: "Veeba",
    category: "Sauces & Spreads",
    description: "India's leading eggless mayo brand. Perfect for wraps and burgers.",
    weight: "250g",
    isVeg: true,
    ingredients: ["Soyabean Oil", "Water", "Sugar", "Milk Solids", "Corn Starch", "Iodised Salt", "Mustard Powder", "Acidity Regulator (INS 260)", "Thickener (INS 415)", "Preservative (INS 211)", "Antioxidant (INS 385)", "Emulsifier (INS 322)"],
    imageUrl: null,
  },
  {
    id: "kissan-mixed-fruit-jam",
    name: "Mixed Fruit Jam",
    brand: "Kissan",
    category: "Sauces & Spreads",
    description: "India's most popular bread spread. Childhood nostalgia in a jar.",
    weight: "200g",
    isVeg: true,
    ingredients: ["Sugar", "Fruit Pulp (Apple, Pineapple, Grape, Mango) (30%)", "Water", "Acidity Regulator (INS 330)", "Gelling Agent (INS 440)", "Preservative (INS 211)", "Color (INS 124)"],
    imageUrl: null,
  },
  {
    id: "funfoods-mayo-garlic",
    name: "Garlic Mayonnaise",
    brand: "Funfoods",
    category: "Sauces & Spreads",
    description: "Dr. Oetker's eggless garlic mayo for Indian snacking.",
    weight: "235g",
    isVeg: true,
    ingredients: ["Soyabean Oil (55%)", "Water", "Sugar", "Garlic Paste (4%)", "Milk Solids", "Iodised Salt", "Acetic Acid (INS 260)", "Mustard Powder", "Thickener (INS 415, INS 412)", "Preservative (INS 211)", "Antioxidant (INS 319)"],
    imageUrl: null,
  },

  // ======================== BREAKFAST & HEALTH ========================
  {
    id: "kelloggs-chocos",
    name: "Chocos Chocolate Cereal",
    brand: "Kellogg's",
    category: "Breakfast & Health",
    description: "India's most popular children's breakfast cereal.",
    weight: "375g",
    isVeg: true,
    ingredients: ["Wheat Flour (61%)", "Sugar", "Cocoa Solids (5.5%)", "Edible Vegetable Oil (Palmolein)", "Malt Extract", "Corn Flour", "Minerals", "Vitamins", "Iodised Salt", "Emulsifier (INS 322)", "Antioxidant (INS 320 BHA)", "Nature Identical Flavoring – Chocolate & Vanilla"],
    imageUrl: null,
  },
  {
    id: "kelloggs-corn-flakes",
    name: "Corn Flakes Original",
    brand: "Kellogg's",
    category: "Breakfast & Health",
    description: "Classic corn flakes cereal. Served with cold milk.",
    weight: "475g",
    isVeg: true,
    ingredients: ["Corn (80%)", "Sugar", "Malt Flavoring", "Iodised Salt", "Minerals (Iron, Zinc)", "Vitamins (C, B1, B2, B3, B6, B12, Folic Acid, A, D)", "Antioxidant (INS 320 BHA)"],
    imageUrl: null,
  },
  {
    id: "saffola-oats",
    name: "Masala Oats Classic Masala",
    brand: "Saffola",
    category: "Breakfast & Health",
    description: "Flavored instant oats. Quick breakfast option marketed as healthy.",
    weight: "39g",
    isVeg: true,
    ingredients: ["Oat Flakes (58%)", "Dehydrated Vegetables (Onion, Potato, Tomato, Peas)", "Corn Starch", "Iodised Salt", "Sugar", "Spices & Condiments", "Edible Vegetable Oil (Palmolein)", "Maltodextrin", "Garlic Powder", "Acidity Regulator (INS 330)"],
    imageUrl: null,
  },
  {
    id: "quaker-oats-original",
    name: "Quaker Oats",
    brand: "Quaker",
    category: "Breakfast & Health",
    description: "Plain rolled oats. Whole grain breakfast cereal.",
    weight: "400g",
    isVeg: true,
    ingredients: ["100% Rolled Oats"],
    imageUrl: null,
  },
  {
    id: "mtr-rava-idli-mix",
    name: "Instant Rava Idli Mix",
    brand: "MTR",
    category: "Breakfast & Health",
    description: "Just add water — instant rava idli in minutes.",
    weight: "200g",
    isVeg: true,
    ingredients: ["Suji (Rava/Semolina)", "Corn Starch", "Cashew Nuts", "Iodised Salt", "Sugar", "Raising Agent (INS 500(ii), INS 450(i))", "Mustard Seeds", "Curry Leaves", "Asafoetida"],
    imageUrl: null,
  },
  {
    id: "mtr-poha",
    name: "Instant Poha",
    brand: "MTR",
    category: "Breakfast & Health",
    description: "Ready-to-cook poha breakfast. Just add water.",
    weight: "180g",
    isVeg: true,
    ingredients: ["Flattened Rice (Poha) (65%)", "Edible Vegetable Oil (Palmolein)", "Iodised Salt", "Sugar", "Peanuts", "Mustard Seeds", "Curry Leaves", "Turmeric", "Dried Green Chilli", "Lemon Powder"],
    imageUrl: null,
  },

  // ======================== ATTA & STAPLES ========================  
  {
    id: "aashirvaad-atta",
    name: "Whole Wheat Atta",
    brand: "Aashirvaad",
    category: "Atta & Staples",
    description: "ITC's flagship atta brand. India's most trusted wheat flour.",
    weight: "5kg",
    isVeg: true,
    ingredients: ["100% Whole Wheat (Gehu)"],
    imageUrl: null,
  },
  {
    id: "aashirvaad-multigrain",
    name: "Multigrain Atta",
    brand: "Aashirvaad",
    category: "Atta & Staples",
    description: "Atta blended with 6 grains for added nutrition.",
    weight: "5kg",
    isVeg: true,
    ingredients: ["Wheat Flour", "Soya Flour (5%)", "Chana Dal Flour (5%)", "Oat Flour (3%)", "Maize Flour (3%)", "Psyllium Husk (1%)"],
    imageUrl: null,
  },
  {
    id: "fortune-maida",
    name: "Refined Wheat Flour (Maida)",
    brand: "Fortune",
    category: "Atta & Staples",
    description: "Refined flour used for naans, parathas, cakes, and pastries.",
    weight: "1kg",
    isVeg: true,
    ingredients: ["100% Refined Wheat Flour (Maida)"],
    imageUrl: null,
  },
  {
    id: "patanjali-atta",
    name: "Whole Wheat Atta",
    brand: "Patanjali",
    category: "Atta & Staples",
    description: "Patanjali's budget-friendly whole wheat flour.",
    weight: "5kg",
    isVeg: true,
    ingredients: ["100% Whole Wheat (Gehu)"],
    imageUrl: null,
  },

  // ======================== ICE CREAM ========================
  {
    id: "kwality-walls-cornetto",
    name: "Cornetto Butterscotch",
    brand: "Kwality Wall's",
    category: "Ice Cream",
    description: "Wafer cone ice cream with butterscotch flavor and nuts.",
    weight: "110ml",
    isVeg: true,
    ingredients: ["Water", "Sugar", "Milk Solids", "Edible Vegetable Fat (Palmolein, Palm Kernel Oil)", "Butterscotch Pieces (4%)", "Wheat Flour", "Liquid Glucose", "Maltodextrin", "Emulsifier (INS 471, INS 322)", "Stabilizer (INS 407, INS 412, INS 410)", "Caramel Color (INS 150d)", "Artificial Flavoring"],
    imageUrl: null,
  },
  {
    id: "amul-ice-cream-vanilla",
    name: "Vanilla Magic Ice Cream",
    brand: "Amul",
    category: "Ice Cream",
    description: "Pure milk ice cream made with Amul dairy. Real milk fat.",
    weight: "750ml",
    isVeg: true,
    ingredients: ["Milk", "Sugar", "Cream", "Skimmed Milk Powder", "Stabilizers (INS 410, INS 412, INS 407)", "Emulsifier (INS 471)", "Nature Identical Flavoring – Vanilla"],
    imageUrl: null,
  },

  // ======================== MORE SNACKS ========================
  {
    id: "haldiram-soan-papdi",
    name: "Soan Papdi",
    brand: "Haldiram's",
    category: "Chocolates & Sweets",
    description: "Flaky, melt-in-mouth Indian sweet. Festival favorite.",
    weight: "250g",
    isVeg: true,
    ingredients: ["Sugar", "Gram Flour (Besan)", "Edible Vegetable Oil (Palmolein)", "Cardamom Powder", "Pistachio Nuts", "Almonds"],
    imageUrl: null,
  },
  {
    id: "britannia-nutri-choice",
    name: "NutriChoice Digestive Biscuits",
    brand: "Britannia",
    category: "Biscuits & Cookies",
    description: "High-fiber digestive biscuit. Marketed as a healthier biscuit option.",
    weight: "100g",
    isVeg: true,
    ingredients: ["Whole Wheat Flour (Atta) (58%)", "Sugar", "Edible Vegetable Oil (Palm Oil)", "Wheat Bran (5%)", "Invert Syrup", "Liquid Glucose", "Oat Flour", "Raising Agents (INS 500(ii), INS 503(ii))", "Iodised Salt", "Emulsifier (INS 322)", "Wheat Gluten"],
    imageUrl: null,
  },
  {
    id: "maggi-pazzta",
    name: "Pazzta Masala Penne",
    brand: "Maggi",
    category: "Instant Noodles",
    description: "Instant pasta from Nestle adapted for Indian taste buds.",
    weight: "64.5g",
    isVeg: true,
    ingredients: ["Pasta (Refined Wheat Flour (Maida), Semolina)", "Edible Vegetable Oil (Palmolein)", "Salt", "Masala Mix (Spices, Maltodextrin, Sugar, Tomato Powder, Onion Powder, Garlic Powder)", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)", "Acidity Regulator (INS 330)"],
    imageUrl: null,
  },
  {
    id: "sundrop-peanut-butter",
    name: "Peanut Butter Crunchy",
    brand: "Sundrop",
    category: "Sauces & Spreads",
    description: "India's popular peanut butter brand. Crunchy variant with peanut pieces.",
    weight: "462g",
    isVeg: true,
    ingredients: ["Roasted Peanuts (90%)", "Sugar", "Edible Vegetable Oil (Palm Oil)", "Iodised Salt", "Hydrogenated Vegetable Fat"],
    imageUrl: null,
  },
  {
    id: "mtr-ready-to-eat-palak",
    name: "Ready to Eat Palak Paneer",
    brand: "MTR",
    category: "Breakfast & Health",
    description: "Shelf-stable ready-to-eat Indian meal. Just heat and serve.",
    weight: "300g",
    isVeg: true,
    ingredients: ["Spinach (35%)", "Paneer (15%)", "Water", "Onion", "Tomato", "Edible Vegetable Oil (Sunflower Oil)", "Cream", "Salt", "Ginger-Garlic Paste", "Spices", "Corn Starch", "Green Chilli"],
    imageUrl: null,
  },
  {
    id: "priya-mango-pickle",
    name: "Mango Pickle (Avakaya)",
    brand: "Priya",
    category: "Masala & Spices",
    description: "South Indian style mango pickle. Every meal's companion.",
    weight: "300g",
    isVeg: true,
    ingredients: ["Raw Mango (60%)", "Edible Vegetable Oil (Sesame Oil)", "Red Chilli Powder", "Iodised Salt", "Fenugreek Powder", "Mustard Powder", "Turmeric", "Acidity Regulator (INS 260)", "Preservative (INS 211)"],
    imageUrl: null,
  },
  {
    id: "tang-orange",
    name: "Tang Orange Instant Drink Mix",
    brand: "Mondelez",
    category: "Beverages",
    description: "Instant orange flavored drink powder. Just add water.",
    weight: "500g",
    isVeg: true,
    ingredients: ["Sugar", "Acidity Regulator (INS 330)", "Minerals (Calcium, Iron, Zinc)", "Vitamins (C, A, B2)", "Thickener (INS 415)", "Color (INS 110 Sunset Yellow)", "Artificial Flavoring – Orange", "Anticaking Agent (INS 551)", "Sweetener (INS 951 Aspartame)"],
    imageUrl: null,
  },
  {
    id: "rasna-orange",
    name: "Orange Drink Concentrate",
    brand: "Rasna",
    category: "Beverages",
    description: "'I Love You Rasna.' Iconic Indian drink concentrate brand.",
    weight: "32g",
    isVeg: true,
    ingredients: ["Sugar", "Citric Acid (INS 330)", "Orange Juice Powder", "Natural & Nature Identical Flavoring", "Color (INS 110)", "Anticaking Agent (INS 551)", "Vitamins (C)"],
    imageUrl: null,
  },
  {
    id: "dabur-real-mango",
    name: "Mango Juice",
    brand: "Real",
    category: "Beverages",
    description: "Premium mango nectar by Dabur. Alphonso mango variant.",
    weight: "200ml",
    isVeg: true,
    ingredients: ["Water", "Mango Pulp (Alphonso 18%)", "Sugar", "Acidity Regulator (INS 330)", "Antioxidant (INS 300)", "Preservative (INS 202)", "Stabilizer (INS 440)"],
    imageUrl: null,
  },
  {
    id: "nescafe-classic",
    name: "Nescafé Classic Instant Coffee",
    brand: "Nestle",
    category: "Beverages",
    description: "India's most popular instant coffee. '100% pure coffee.'",
    weight: "50g",
    isVeg: true,
    ingredients: ["100% Pure Instant Coffee (Spray Dried)"],
    imageUrl: null,
  },
  {
    id: "bru-instant-coffee",
    name: "Bru Instant Coffee",
    brand: "Bru",
    category: "Beverages",
    description: "Hindustan Unilever's coffee brand. South India's favorite filter coffee style.",
    weight: "50g",
    isVeg: true,
    ingredients: ["Coffee (70%)", "Chicory (30%)"],
    imageUrl: null,
  },
  {
    id: "maggi-masala-ae-magic",
    name: "Masala-ae-Magic",
    brand: "Maggi",
    category: "Masala & Spices",
    description: "All-purpose seasoning sachet. Sprinkle on anything for instant flavor.",
    weight: "6g",
    isVeg: true,
    ingredients: ["Iodized Salt", "Mixed Spices & Condiments", "Maltodextrin", "Sugar", "Anticaking Agent (INS 551)", "Hydrolyzed Vegetable Protein", "Flavor Enhancer (INS 627)", "Flavor Enhancer (INS 631)", "Onion Powder", "Garlic Powder"],
    imageUrl: null,
  },
  {
    id: "lijjat-papad",
    name: "Lijjat Papad Udad Plain",
    brand: "Lijjat",
    category: "Atta & Staples",
    description: "India's iconic women's cooperative papad brand.",
    weight: "200g",
    isVeg: true,
    ingredients: ["Urid Dal Flour (Black Gram)", "Edible Common Salt", "Asafoetida", "Black Pepper", "Edible Oil (Groundnut Oil)", "Papad Khar (INS 500(ii))"],
    imageUrl: null,
  },
];

// Helper: get all unique categories
export function getCategories(): ProductCategory[] {
  const catSet = new Set<ProductCategory>();
  INDIAN_PRODUCTS.forEach(p => catSet.add(p.category));
  return Array.from(catSet);
}

// Helper: get trending products (curated popular 8)
export function getTrendingProducts(): IndianProduct[] {
  const trendingIds = [
    "maggi-masala-2min",
    "lays-magic-masala",
    "parle-g-original",
    "coca-cola-original",
    "cadbury-dairy-milk",
    "kurkure-masala-munch",
    "haldiram-aloo-bhujia",
    "sunfeast-dark-fantasy",
  ];
  return trendingIds.map(id => INDIAN_PRODUCTS.find(p => p.id === id)!).filter(Boolean);
}

// Helper: search products with fuzzy matching
export function searchProducts(query: string): IndianProduct[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  // Score each product for relevance
  const scored = INDIAN_PRODUCTS.map(product => {
    let score = 0;
    const name = product.name.toLowerCase();
    const brand = product.brand.toLowerCase();
    const category = product.category.toLowerCase();
    const description = product.description.toLowerCase();

    // Exact brand match gets highest score
    if (brand === q) score += 100;
    // Brand starts with query
    else if (brand.startsWith(q)) score += 80;
    // Brand contains query
    else if (brand.includes(q)) score += 60;

    // Name contains query
    if (name.includes(q)) score += 50;

    // Category match
    if (category.includes(q)) score += 40;

    // Description match
    if (description.includes(q)) score += 20;

    // Check individual words in query
    const words = q.split(/\s+/);
    for (const word of words) {
      if (word.length < 2) continue;
      if (brand.includes(word)) score += 30;
      if (name.includes(word)) score += 25;
      if (category.includes(word)) score += 15;
      if (description.includes(word)) score += 10;
      // Check ingredients
      if (product.ingredients.some(ing => ing.toLowerCase().includes(word))) {
        score += 5;
      }
    }

    return { product, score };
  });

  // Return products with score > 0, sorted by relevance, max 16
  return scored
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 16)
    .map(s => s.product);
}
