import { PrismaClient } from '@prisma/client';
import { scoreProduct } from './scoring';
const prisma = new PrismaClient();

const EXTRA_PRODUCTS = [
  // BEVERAGES
  {id:"fanta-orange",name:"Fanta Orange",brand:"Coca-Cola",category:"Beverages",description:"Orange-flavored carbonated soft drink.",weight:"300ml",isVeg:true,ingredients:["Carbonated Water","Sugar","Acidity Regulators (INS 330, INS 331(iii))","Stabilizer (INS 444)","Preservative (INS 211)","Color (INS 110)","Antioxidant (INS 300)","Natural Flavoring Substances"]},
  {id:"7up-lemon",name:"7UP",brand:"PepsiCo",category:"Beverages",description:"Lemon-lime flavored carbonated drink.",weight:"300ml",isVeg:true,ingredients:["Carbonated Water","Sugar","Acidity Regulator (INS 330)","Natural Flavoring Substances"]},
  {id:"mirinda-orange",name:"Mirinda Orange",brand:"PepsiCo",category:"Beverages",description:"Orange-flavored carbonated drink from PepsiCo.",weight:"300ml",isVeg:true,ingredients:["Carbonated Water","Sugar","Acidity Regulators (INS 330, INS 331(iii))","Stabilizer (INS 444)","Preservative (INS 211)","Color (INS 110)","Antioxidant (INS 300)","Natural Flavoring Substances"]},
  {id:"sting-energy-drink",name:"Sting Energy Drink",brand:"PepsiCo",category:"Beverages",description:"Affordable energy drink popular among youth.",weight:"250ml",isVeg:true,ingredients:["Carbonated Water","Sugar","Acidity Regulators (INS 330, INS 331(iii))","Taurine","Caffeine","Inositol","Niacinamide","Preservative (INS 211)","Color (INS 110)","Artificial Flavoring"]},
  {id:"red-bull-energy",name:"Red Bull Energy Drink",brand:"Red Bull",category:"Beverages",description:"Premium energy drink. Gives You Wings.",weight:"250ml",isVeg:true,ingredients:["Carbonated Water","Sucrose","Glucose","Acidity Regulator (INS 330)","Taurine","Caffeine","Glucuronolactone","Inositol","Niacinamide","Vitamin B6","Vitamin B12","Natural Flavoring"]},
  {id:"cadbury-oreo-milkshake",name:"Oreo Milkshake",brand:"Cadbury",category:"Beverages",description:"Ready-to-drink Oreo flavored milkshake.",weight:"180ml",isVeg:true,ingredients:["Toned Milk","Sugar","Cocoa Solids (2%)","Oreo Cookie Pieces (2%)","Milk Solids","Stabilizers (INS 407, INS 466)","Emulsifier (INS 471)","Nature Identical Flavoring","Color (INS 150d)"]},
  {id:"britannia-winkin-cow-choco",name:"Winkin Cow Chocolate Milkshake",brand:"Britannia",category:"Beverages",description:"Thick chocolate milkshake in tetra pack.",weight:"180ml",isVeg:true,ingredients:["Toned Milk","Sugar","Cocoa Powder (2.5%)","Milk Solids","Stabilizers (INS 407, INS 466)","Emulsifier (INS 471)","Nature Identical Flavoring - Chocolate"]},
  {id:"paperboat-jaljeera",name:"Jaljeera",brand:"Paper Boat",category:"Beverages",description:"Traditional Indian spiced cumin drink.",weight:"250ml",isVeg:true,ingredients:["Water","Sugar","Cumin Extract","Mint Extract","Black Salt","Iodised Salt","Spices","Acidity Regulator (INS 330)","Preservative (INS 211)"]},
  {id:"raw-pressery-orange",name:"Valencia Orange Juice",brand:"Raw Pressery",category:"Beverages",description:"Cold-pressed orange juice with no added sugar.",weight:"250ml",isVeg:true,ingredients:["Orange Juice (100%)"]},
  {id:"dabur-real-pomegranate",name:"Real Pomegranate Juice",brand:"Real",category:"Beverages",description:"Pomegranate juice drink.",weight:"200ml",isVeg:true,ingredients:["Water","Pomegranate Juice Concentrate","Sugar","Acidity Regulator (INS 330)","Preservative (INS 211)","Antioxidant (INS 300)","Color (INS 124)"]},
  {id:"bisleri-mineral-water",name:"Bisleri Mineral Water",brand:"Bisleri",category:"Beverages",description:"India's most trusted packaged drinking water.",weight:"1L",isVeg:true,ingredients:["Purified Water","Added Minerals (Potassium Chloride, Sodium Bicarbonate)"]},
  {id:"amul-kool-badam",name:"Kool Badam Milk",brand:"Amul",category:"Dairy",description:"Almond flavored milk drink.",weight:"200ml",isVeg:true,ingredients:["Toned Milk","Sugar","Almond Paste (2%)","Stabilizer (INS 407)","Cardamom","Saffron Extract","Nature Identical Flavoring - Badam"]},
  // DAIRY
  {id:"amul-ghee",name:"Amul Pure Ghee",brand:"Amul",category:"Dairy",description:"Pure cow ghee. Essential for Indian cooking.",weight:"500ml",isVeg:true,ingredients:["Cow Milk Fat (99.7%)"]},
  {id:"mother-dairy-paneer",name:"Mother Dairy Paneer",brand:"Mother Dairy",category:"Dairy",description:"Fresh cottage cheese for Indian cooking.",weight:"200g",isVeg:true,ingredients:["Pasteurised Toned Milk","Citric Acid (INS 330)"]},
  {id:"amul-lassi-mango",name:"Kool Mango Lassi",brand:"Amul",category:"Dairy",description:"Ready-to-drink mango flavored lassi.",weight:"200ml",isVeg:true,ingredients:["Toned Milk","Sugar","Mango Pulp (5%)","Stabilizer (INS 407)","Acidity Regulator (INS 330)","Preservative (INS 202)","Nature Identical Flavoring - Mango"]},
  {id:"amul-chocolate-milk",name:"Amul Kool Chocolate",brand:"Amul",category:"Dairy",description:"Flavored milk drink with chocolate.",weight:"200ml",isVeg:true,ingredients:["Toned Milk","Sugar","Cocoa Powder (2%)","Stabilizer (INS 407, INS 466)","Emulsifier (INS 322)","Nature Identical Flavoring - Chocolate"]},
  {id:"epigamia-greek-yogurt",name:"Greek Yogurt Strawberry",brand:"Epigamia",category:"Dairy",description:"Premium Greek yogurt with fruit.",weight:"90g",isVeg:true,ingredients:["Pasteurised Toned Milk","Sugar","Strawberry Fruit Prep (8%)","Milk Protein Concentrate","Active Cultures","Stabilizer (INS 440)","Acidity Regulator (INS 330)","Natural Flavoring"]},
  {id:"nestle-milkmaid",name:"Milkmaid Sweetened Condensed Milk",brand:"Nestle",category:"Dairy",description:"Sweetened condensed milk for desserts.",weight:"400g",isVeg:true,ingredients:["Milk","Sugar"]},
  {id:"amul-cream",name:"Amul Fresh Cream",brand:"Amul",category:"Dairy",description:"Fresh dairy cream for cooking and desserts.",weight:"200ml",isVeg:true,ingredients:["Pasteurised Cream (Fat 25%)","Stabilizer (INS 407)"]},
  {id:"go-cheese-spread",name:"Go Cheese Spread Plain",brand:"Go",category:"Dairy",description:"Spreadable processed cheese.",weight:"200g",isVeg:true,ingredients:["Cheese (51%)","Water","Butter","Milk Solids","Emulsifying Salts (INS 331(iii), INS 452(i))","Iodised Salt","Preservative (INS 200)","Acidity Regulator (INS 330)"]},
  {id:"yakult-probiotic",name:"Yakult Probiotic Drink",brand:"Yakult",category:"Dairy",description:"Probiotic fermented milk drink.",weight:"65ml",isVeg:true,ingredients:["Water","Sugar","Skimmed Milk Powder","Glucose","Natural Flavoring","Lactobacillus casei strain Shirota"]},
  // COOKING OIL
  {id:"fortune-sunflower-oil",name:"Sunlite Refined Sunflower Oil",brand:"Fortune",category:"Cooking Oil",description:"Light refined sunflower oil for everyday cooking.",weight:"1L",isVeg:true,ingredients:["Refined Sunflower Oil","Antioxidant (INS 319)","Vitamin A","Vitamin D2"]},
  {id:"dhara-mustard-oil",name:"Dhara Kachi Ghani Mustard Oil",brand:"Dhara",category:"Cooking Oil",description:"Popular mustard oil brand in North India.",weight:"1L",isVeg:true,ingredients:["Mustard Oil (Cold Pressed)"]},
  {id:"sundrop-heart",name:"Sundrop Heart Blended Oil",brand:"Sundrop",category:"Cooking Oil",description:"Blended oil with sunflower and rice bran.",weight:"1L",isVeg:true,ingredients:["Refined Sunflower Oil (70%)","Refined Rice Bran Oil (30%)","Antioxidant (INS 319)","Anti-foaming Agent (INS 900a)"]},
  {id:"patanjali-coconut-oil",name:"Virgin Coconut Oil",brand:"Patanjali",category:"Cooking Oil",description:"Cold-pressed virgin coconut oil.",weight:"500ml",isVeg:true,ingredients:["Virgin Coconut Oil (Cold Pressed)"]},
  {id:"fortune-rice-bran-oil",name:"Rice Bran Health Oil",brand:"Fortune",category:"Cooking Oil",description:"Rice bran oil with oryzanol for heart health.",weight:"1L",isVeg:true,ingredients:["Refined Rice Bran Oil","Antioxidant (INS 319)","Anti-foaming Agent (INS 900a)","Vitamin A","Vitamin D2"]},
  {id:"oleev-olive-oil",name:"Oleev Active Olive Oil",brand:"Oleev",category:"Cooking Oil",description:"Blended olive oil for Indian cooking.",weight:"1L",isVeg:true,ingredients:["Refined Olive Oil (80%)","Extra Virgin Olive Oil (20%)"]},
  {id:"saffola-total",name:"Saffola Total Pro Heart Oil",brand:"Saffola",category:"Cooking Oil",description:"Blended oil with LOSORB technology claim.",weight:"1L",isVeg:true,ingredients:["Refined Rice Bran Oil","Refined Safflower Oil","Antioxidant (INS 319)","Anti-foaming Agent (INS 900a)","Vitamin A","Vitamin D2"]},
  // MASALA & SPICES
  {id:"mdh-deggi-mirch",name:"Deggi Mirch",brand:"MDH",category:"Masala & Spices",description:"Bright red chilli powder for color and mild heat.",weight:"100g",isVeg:true,ingredients:["Red Chilli (Kashmiri)","Red Chilli (Guntur)"]},
  {id:"catch-turmeric-powder",name:"Turmeric Powder",brand:"Catch",category:"Masala & Spices",description:"Pure turmeric powder for cooking.",weight:"100g",isVeg:true,ingredients:["Turmeric"]},
  {id:"everest-pav-bhaji-masala",name:"Pav Bhaji Masala",brand:"Everest",category:"Masala & Spices",description:"Spice blend for Mumbai's iconic street food.",weight:"100g",isVeg:true,ingredients:["Coriander","Red Chilli","Cumin","Dry Mango","Black Pepper","Cassia","Clove","Cardamom","Dry Ginger","Iodised Salt","Citric Acid (INS 330)"]},
  {id:"mdh-biryani-masala",name:"Hyderabadi Biryani Masala",brand:"MDH",category:"Masala & Spices",description:"Spice blend for authentic Hyderabadi biryani.",weight:"100g",isVeg:true,ingredients:["Coriander","Cumin","Red Chilli","Black Pepper","Cassia","Clove","Cardamom","Mace","Nutmeg","Bay Leaf","Star Anise","Iodised Salt"]},
  {id:"everest-sambhar-masala",name:"Sambhar Masala",brand:"Everest",category:"Masala & Spices",description:"South Indian sambhar spice blend.",weight:"100g",isVeg:true,ingredients:["Coriander","Red Chilli","Cumin","Fenugreek","Turmeric","Black Pepper","Mustard","Asafoetida","Curry Leaves","Iodised Salt"]},
  {id:"suhana-chicken-masala",name:"Chicken Masala",brand:"Suhana",category:"Masala & Spices",description:"Ready-to-use chicken curry masala.",weight:"100g",isVeg:true,ingredients:["Coriander","Red Chilli","Cumin","Turmeric","Black Pepper","Cassia","Clove","Cardamom","Iodised Salt","Garlic Powder","Ginger Powder","Onion Powder"]},
  {id:"mtr-rasam-powder",name:"Rasam Powder",brand:"MTR",category:"Masala & Spices",description:"Traditional South Indian rasam spice mix.",weight:"100g",isVeg:true,ingredients:["Coriander","Red Chilli","Cumin","Black Pepper","Fenugreek","Turmeric","Curry Leaves","Asafoetida"]},
  // BREAKFAST & HEALTH
  {id:"kelloggs-muesli-fruit-nut",name:"Muesli Fruit & Nut",brand:"Kellogg's",category:"Breakfast & Health",description:"Muesli with dried fruits and nuts.",weight:"500g",isVeg:true,ingredients:["Whole Wheat Flakes (40%)","Oat Flakes (20%)","Sugar","Raisins","Almonds","Cashews","Corn Flakes","Rice Flakes","Honey","Iodised Salt","Emulsifier (INS 322)","Antioxidant (INS 320)"]},
  {id:"yoga-bar-muesli",name:"Muesli Dark Chocolate & Cranberry",brand:"Yoga Bar",category:"Breakfast & Health",description:"Premium muesli with dark chocolate chunks.",weight:"400g",isVeg:true,ingredients:["Rolled Oats (45%)","Wheat Flakes","Dark Chocolate Chips (10%)","Dried Cranberries","Almonds","Pumpkin Seeds","Honey","Coconut Oil","Iodised Salt"]},
  {id:"bagrry-corn-flakes-plus",name:"Corn Flakes Plus",brand:"Bagrry's",category:"Breakfast & Health",description:"Corn flakes with added almonds and raisins.",weight:"475g",isVeg:true,ingredients:["Corn Grits (80%)","Sugar","Almonds (3%)","Raisins (3%)","Malt Extract","Iodised Salt","Vitamins","Minerals"]},
  {id:"mtr-upma-mix",name:"Upma Mix",brand:"MTR",category:"Breakfast & Health",description:"Instant upma breakfast mix.",weight:"200g",isVeg:true,ingredients:["Semolina (Rava) (75%)","Edible Vegetable Oil (Palmolein)","Iodised Salt","Cashew Nuts","Bengal Gram Dal","Curry Leaves","Mustard Seeds","Green Chilli","Turmeric"]},
  {id:"mtr-poha-mix",name:"Poha Mix",brand:"MTR",category:"Breakfast & Health",description:"Instant poha breakfast mix.",weight:"180g",isVeg:true,ingredients:["Flattened Rice (Poha) (70%)","Edible Vegetable Oil (Palmolein)","Peanuts","Iodised Salt","Sugar","Curry Leaves","Mustard Seeds","Turmeric","Green Chilli"]},
  {id:"saffola-oats-veggie-twist",name:"Masala Oats Veggie Twist",brand:"Saffola",category:"Breakfast & Health",description:"Oats with mixed vegetable masala flavor.",weight:"39g",isVeg:true,ingredients:["Rolled Oats (70%)","Maltodextrin","Salt","Spices","Dried Vegetables","Sugar","Hydrolyzed Vegetable Protein","Flavor Enhancer (INS 627, INS 631)","Acidity Regulator (INS 330)"]},
  {id:"true-elements-granola",name:"Crunchy Muesli with Fruits",brand:"True Elements",category:"Breakfast & Health",description:"Premium granola with dried fruits.",weight:"400g",isVeg:true,ingredients:["Rolled Oats (50%)","Honey","Rice Bran Oil","Dried Cranberries","Raisins","Almonds","Pumpkin Seeds","Sunflower Seeds","Flax Seeds","Iodised Salt"]},
  {id:"protinex-original",name:"Protinex Original",brand:"Protinex",category:"Breakfast & Health",description:"Protein supplement powder for adults.",weight:"400g",isVeg:true,ingredients:["Hydrolyzed Protein (Soy, Casein)","Maltodextrin","Sugar","Skimmed Milk Powder","Minerals","Vitamins","Emulsifier (INS 322)","Acidity Regulator (INS 330)","Artificial Flavoring"]},
  {id:"ensure-vanilla",name:"Ensure Vanilla",brand:"Abbott",category:"Breakfast & Health",description:"Complete nutrition drink for adults.",weight:"400g",isVeg:true,ingredients:["Maltodextrin","Sugar","Milk Protein Concentrate","Soy Protein Isolate","Edible Vegetable Oil (Canola, Soy)","Minerals","Vitamins","Emulsifier (INS 322)","Stabilizer (INS 407)","Artificial Flavoring - Vanilla"]},
  {id:"soulfull-ragi-bites",name:"Ragi Bites Choco Fills",brand:"Soulfull",category:"Breakfast & Health",description:"Ragi-based cereal with chocolate filling for kids.",weight:"250g",isVeg:true,ingredients:["Ragi Flour (40%)","Sugar","Refined Wheat Flour (Maida)","Cocoa Solids (5%)","Edible Vegetable Oil (Palm Oil)","Malt Extract","Iodised Salt","Emulsifier (INS 322)","Raising Agent (INS 500(ii))","Artificial Flavoring - Chocolate"]},
  {id:"mtr-ready-dal-fry",name:"Ready to Eat Dal Fry",brand:"MTR",category:"Breakfast & Health",description:"Ready-to-eat dal fry in retort pouch.",weight:"300g",isVeg:true,ingredients:["Water","Toor Dal (25%)","Tomato","Onion","Edible Vegetable Oil (Palmolein)","Iodised Salt","Spices","Garlic","Ginger","Green Chilli","Coriander Leaves"]},
  {id:"mtr-ready-palak-paneer",name:"Ready to Eat Palak Paneer",brand:"MTR",category:"Breakfast & Health",description:"Ready-to-eat spinach and cottage cheese curry.",weight:"300g",isVeg:true,ingredients:["Water","Spinach (20%)","Paneer (15%)","Onion","Edible Vegetable Oil (Palmolein)","Cream","Iodised Salt","Spices","Garlic","Ginger","Cashew Paste"]},
  {id:"haldiram-minute-khana-dal-makhani",name:"Minute Khana Dal Makhani",brand:"Haldiram's",category:"Breakfast & Health",description:"Ready-to-eat dal makhani.",weight:"300g",isVeg:true,ingredients:["Water","Black Gram Dal (20%)","Kidney Beans (5%)","Tomato Puree","Cream","Butter","Edible Vegetable Oil (Palmolein)","Iodised Salt","Spices","Garlic","Ginger"]},
  {id:"gits-dhokla-mix",name:"Dhokla Mix",brand:"Gits",category:"Breakfast & Health",description:"Instant Gujarati dhokla mix.",weight:"200g",isVeg:true,ingredients:["Bengal Gram Flour (60%)","Rice Flour","Sugar","Iodised Salt","Citric Acid (INS 330)","Raising Agent (INS 500(ii))","Spices","Ginger Powder"]},
  // SAUCES & SPREADS
  {id:"veeba-chipotle-southwest",name:"Chipotle Southwest Sauce",brand:"Veeba",category:"Sauces & Spreads",description:"Subway-style chipotle sauce for sandwiches.",weight:"300g",isVeg:true,ingredients:["Refined Soybean Oil","Water","Sugar","Chipotle Pepper (3%)","Iodised Salt","Vinegar","Emulsifiers (INS 1442, INS 415)","Preservatives (INS 211, INS 202)","Spices","Garlic Powder","Acidity Regulator (INS 260)"]},
  {id:"ching-schezwan-chutney",name:"Schezwan Chutney",brand:"Ching's Secret",category:"Sauces & Spreads",description:"Spicy Indo-Chinese chutney for noodles and momos.",weight:"250g",isVeg:true,ingredients:["Edible Vegetable Oil (Soybean)","Red Chilli (15%)","Garlic","Onion","Soy Sauce","Sugar","Iodised Salt","Vinegar","Ginger","Acidity Regulator (INS 260)","Preservative (INS 211)"]},
  {id:"del-monte-pasta-sauce",name:"Pasta Sauce Cheesy Tomato",brand:"Del Monte",category:"Sauces & Spreads",description:"Ready-to-use pasta sauce.",weight:"400g",isVeg:true,ingredients:["Tomato Puree (60%)","Water","Sugar","Cheese Powder (3%)","Iodised Salt","Edible Vegetable Oil (Palmolein)","Onion Powder","Garlic Powder","Spices","Thickener (INS 1422)","Acidity Regulator (INS 330)","Preservative (INS 211)"]},
  {id:"kissan-peanut-butter-creamy",name:"Peanut Butter Creamy",brand:"Kissan",category:"Sauces & Spreads",description:"Peanut butter spread for bread.",weight:"350g",isVeg:true,ingredients:["Roasted Peanuts (85%)","Sugar","Edible Vegetable Oil (Palm Oil)","Iodised Salt","Emulsifier (INS 471)"]},
  {id:"maggi-pichkoo-ketchup",name:"Pichkoo Tomato Ketchup",brand:"Maggi",category:"Sauces & Spreads",description:"Small squeeze pack ketchup for kids.",weight:"90g",isVeg:true,ingredients:["Water","Tomato Paste (25%)","Sugar","Salt","Acidity Regulator (INS 260)","Thickener (INS 1422)","Preservative (INS 211)","Spices"]},
  {id:"weikfield-pasta-sauce",name:"Pasta & Pizza Sauce",brand:"Weikfield",category:"Sauces & Spreads",description:"Tomato-based sauce for pasta and pizza.",weight:"200g",isVeg:true,ingredients:["Tomato Puree (55%)","Water","Sugar","Iodised Salt","Edible Vegetable Oil (Palmolein)","Onion","Garlic","Spices","Thickener (INS 1422)","Acidity Regulator (INS 330)","Preservative (INS 211)"]},
  {id:"hellmanns-mayonnaise",name:"Real Mayonnaise",brand:"Hellmann's",category:"Sauces & Spreads",description:"Premium egg-based mayonnaise.",weight:"275g",isVeg:false,ingredients:["Refined Soybean Oil","Water","Egg Yolk (5%)","Sugar","Iodised Salt","Vinegar","Lemon Juice","Emulsifier (INS 415)","Preservative (INS 202)","Antioxidant (INS 385)"]},
  {id:"dabur-honey",name:"Dabur Honey",brand:"Dabur",category:"Sauces & Spreads",description:"India's most trusted honey brand.",weight:"500g",isVeg:true,ingredients:["Honey"]},
  {id:"maggi-bhuna-masala",name:"Bhuna Masala",brand:"Maggi",category:"Sauces & Spreads",description:"Ready-to-use wet masala paste for curries.",weight:"65g",isVeg:true,ingredients:["Onion","Tomato","Edible Vegetable Oil (Palmolein)","Ginger","Garlic","Iodised Salt","Spices","Sugar","Acidity Regulator (INS 260)","Thickener (INS 1422)"]},
  // ATTA & STAPLES
  {id:"aashirvaad-multigrain-atta",name:"Multigrain Atta",brand:"Aashirvaad",category:"Atta & Staples",description:"Multigrain flour with 6 grains.",weight:"5kg",isVeg:true,ingredients:["Whole Wheat Flour","Soya Flour","Oat Flour","Ragi Flour","Maize Flour","Psyllium Husk (Isabgol)"]},
  {id:"fortune-suji",name:"Suji (Semolina)",brand:"Fortune",category:"Atta & Staples",description:"Fine semolina for upma, halwa, and rava dosa.",weight:"500g",isVeg:true,ingredients:["Semolina (Wheat)"]},
  {id:"tata-salt",name:"Tata Salt Iodised",brand:"Tata",category:"Atta & Staples",description:"India's most trusted iodised salt. Desh Ka Namak.",weight:"1kg",isVeg:true,ingredients:["Iodised Salt","Potassium Iodate"]},
  {id:"daawat-basmati",name:"Daawat Rozana Basmati Rice",brand:"Daawat",category:"Atta & Staples",description:"Everyday basmati rice for daily cooking.",weight:"1kg",isVeg:true,ingredients:["Basmati Rice"]},
  {id:"lijjat-papad-udad",name:"Udad Papad",brand:"Lijjat",category:"Atta & Staples",description:"Traditional udad dal papad from the women's cooperative.",weight:"200g",isVeg:true,ingredients:["Udad Dal Flour","Edible Vegetable Oil (Palmolein)","Iodised Salt","Black Pepper","Asafoetida","Raising Agent (INS 500(ii))"]},
  // ICE CREAM
  {id:"kwality-walls-magnum",name:"Magnum Classic",brand:"Kwality Wall's",category:"Ice Cream",description:"Premium Belgian chocolate coated ice cream bar.",weight:"80ml",isVeg:true,ingredients:["Milk","Sugar","Cocoa Butter","Cocoa Mass","Milk Solids","Cream","Emulsifier (INS 322, INS 471)","Stabilizers (INS 412, INS 407)","Vanilla Extract"]},
  {id:"amul-chocobar",name:"Amul Chocobar",brand:"Amul",category:"Ice Cream",description:"Chocolate-coated vanilla ice cream bar.",weight:"65ml",isVeg:true,ingredients:["Milk","Sugar","Chocolate Coating (Sugar, Cocoa Butter, Cocoa Mass, Milk Solids, Emulsifier INS 322)","Milk Solids","Emulsifier (INS 471)","Stabilizers (INS 412, INS 407)","Artificial Flavoring - Vanilla"]},
  {id:"naturals-tender-coconut",name:"Tender Coconut Ice Cream",brand:"Naturals",category:"Ice Cream",description:"Premium ice cream made with real tender coconut.",weight:"500ml",isVeg:true,ingredients:["Milk","Sugar","Tender Coconut Water (15%)","Coconut Flesh (8%)","Milk Solids","Stabilizer (INS 412)"]},
  {id:"kwality-walls-selection-butterscotch",name:"Selection Butterscotch",brand:"Kwality Wall's",category:"Ice Cream",description:"Frozen dessert with butterscotch flavor and caramel sauce.",weight:"700ml",isVeg:true,ingredients:["Water","Sugar","Edible Vegetable Fat (Palm Oil)","Milk Solids","Liquid Glucose","Butterscotch Pieces","Emulsifiers (INS 471, INS 477)","Stabilizers (INS 412, INS 410, INS 407)","Color (INS 150c)","Artificial Flavoring - Butterscotch"]},
  {id:"havmor-kesar-pista",name:"Kesar Pista Ice Cream",brand:"Havmor",category:"Ice Cream",description:"Traditional Indian ice cream with saffron and pistachio.",weight:"500ml",isVeg:true,ingredients:["Milk","Sugar","Milk Solids","Pistachios (3%)","Saffron Extract","Cardamom","Emulsifier (INS 471)","Stabilizers (INS 412, INS 407)","Color (INS 102)"]},
  {id:"baskin-robbins-chocolate-fudge",name:"Chocolate Fudge Brownie",brand:"Baskin Robbins",category:"Ice Cream",description:"Premium chocolate ice cream with brownie pieces.",weight:"500ml",isVeg:true,ingredients:["Milk","Sugar","Cream","Cocoa Solids (8%)","Brownie Pieces (Wheat Flour, Sugar, Cocoa, Palm Oil)","Milk Solids","Emulsifier (INS 471)","Stabilizers (INS 412, INS 407)","Artificial Flavoring - Chocolate"]},
  {id:"mother-dairy-fruit-bar-orange",name:"Fruit Bar Orange",brand:"Mother Dairy",category:"Ice Cream",description:"Frozen fruit bar with orange flavor.",weight:"65ml",isVeg:true,ingredients:["Water","Sugar","Orange Juice Concentrate (5%)","Acidity Regulator (INS 330)","Stabilizer (INS 412)","Color (INS 110)","Nature Identical Flavoring - Orange"]},
  // CHOCOLATES & SWEETS (new)
  {id:"snickers-bar",name:"Snickers Bar",brand:"Mars",category:"Chocolates & Sweets",description:"Chocolate bar with peanuts, caramel, and nougat.",weight:"50g",isVeg:true,ingredients:["Sugar","Peanuts (22%)","Glucose Syrup","Skimmed Milk Powder","Cocoa Butter","Cocoa Mass","Vegetable Fat (Palm Oil)","Lactose","Milk Fat","Hydrogenated Palm Oil","Emulsifier (INS 322)","Iodised Salt","Egg White Powder","Artificial Flavoring - Vanilla"]},
  {id:"cadbury-celebrations",name:"Celebrations Assorted Pack",brand:"Cadbury",category:"Chocolates & Sweets",description:"Gift box with assorted Cadbury chocolates.",weight:"136g",isVeg:true,ingredients:["Sugar","Cocoa Butter","Milk Solids","Cocoa Solids","Vegetable Fat (Palm Oil)","Almonds","Raisins","Emulsifier (INS 322, INS 442, INS 476)","Glucose Syrup","Invert Sugar","Iodised Salt","Nature Identical Flavoring"]},
  {id:"cadbury-fuse",name:"Fuse Chocolate Bar",brand:"Cadbury",category:"Chocolates & Sweets",description:"Chocolate bar with peanuts, raisins, and caramel.",weight:"45g",isVeg:true,ingredients:["Sugar","Peanuts (15%)","Glucose Syrup","Milk Solids","Cocoa Butter","Cocoa Solids","Vegetable Fat (Palm Oil)","Raisins","Maltodextrin","Emulsifier (INS 322)","Iodised Salt","Artificial Flavoring"]},
  {id:"nestle-milkybar",name:"Milkybar White Chocolate",brand:"Nestle",category:"Chocolates & Sweets",description:"White chocolate bar for kids.",weight:"25g",isVeg:true,ingredients:["Sugar","Whole Milk Powder (26%)","Cocoa Butter (24%)","Whey Powder","Emulsifier (INS 322)","Nature Identical Flavoring - Vanilla"]},
  {id:"cadbury-bournville",name:"Bournville Dark Chocolate",brand:"Cadbury",category:"Chocolates & Sweets",description:"Premium dark chocolate with rich cocoa flavor.",weight:"80g",isVeg:true,ingredients:["Sugar","Cocoa Mass (35%)","Cocoa Butter","Emulsifier (INS 442, INS 476)","Nature Identical Flavoring - Vanilla"]},
  {id:"melody-toffee",name:"Melody Chocolaty Toffee",brand:"Parle",category:"Chocolates & Sweets",description:"Iconic toffee with chocolate filling.",weight:"5g",isVeg:true,ingredients:["Sugar","Liquid Glucose","Hydrogenated Vegetable Fat","Cocoa Solids","Milk Solids","Emulsifier (INS 322)","Iodised Salt","Artificial Flavoring - Chocolate & Caramel","INS 150c"]},
  {id:"mango-bite-toffee",name:"Mango Bite Toffee",brand:"Parle",category:"Chocolates & Sweets",description:"Mango-flavored toffee. Childhood favorite.",weight:"4g",isVeg:true,ingredients:["Sugar","Liquid Glucose","Hydrogenated Vegetable Fat","Acidity Regulator (INS 330)","Emulsifier (INS 322)","Artificial Flavoring - Mango","Color (INS 102)"]},
  {id:"pulse-candy-guava",name:"Pulse Candy Guava",brand:"DS Group",category:"Chocolates & Sweets",description:"Tangy hard candy with spicy center.",weight:"4g",isVeg:true,ingredients:["Sugar","Liquid Glucose","Acidity Regulators (INS 330, INS 296)","Iodised Salt","Spices","Nature Identical Flavoring - Guava","Color (INS 143)"]},
  {id:"center-fresh-mint",name:"Center Fresh Spearmint",brand:"Perfetti",category:"Chocolates & Sweets",description:"Chewing gum with liquid center.",weight:"4g",isVeg:true,ingredients:["Sugar","Gum Base","Glucose Syrup","Glycerol (INS 422)","Acidity Regulator (INS 330)","Emulsifier (INS 322)","Artificial Sweetener (INS 951)","Artificial Flavoring - Spearmint","Color (INS 133)","Glazing Agent (INS 903)"]},
  {id:"eclairs-gold-toffee",name:"Cadbury Choclairs Gold",brand:"Cadbury",category:"Chocolates & Sweets",description:"Caramel toffee with chocolate center.",weight:"5.5g",isVeg:true,ingredients:["Sugar","Liquid Glucose","Hydrogenated Vegetable Fat","Cocoa Solids","Milk Solids","Emulsifier (INS 322)","Iodised Salt","Artificial Flavoring - Chocolate & Caramel"]},
  {id:"mtr-gulab-jamun-mix",name:"Gulab Jamun Mix",brand:"MTR",category:"Chocolates & Sweets",description:"Instant gulab jamun mix. Just add water.",weight:"200g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Sugar","Milk Solids (20%)","Edible Vegetable Oil (Palm Oil)","Raising Agent (INS 500(ii))","Cardamom"]},
  // INSTANT NOODLES (new)
  {id:"maggi-hot-heads-peri-peri",name:"Hot Heads Peri Peri Noodles",brand:"Maggi",category:"Instant Noodles",description:"Spicy variant targeting young adults.",weight:"71g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Palm Oil","Iodised Salt","Wheat Gluten","Spices","Chilli Flakes","Maltodextrin","Sugar","Flavor Enhancer (INS 627)","Flavor Enhancer (INS 631)","Acidity Regulator (INS 330)","Onion Powder","Garlic Powder"]},
  {id:"yippee-power-up-masala",name:"Power Up Masala Noodles",brand:"Sunfeast Yippee",category:"Instant Noodles",description:"Atta-based noodles from ITC.",weight:"70g",isVeg:true,ingredients:["Whole Wheat Flour (Atta) (70%)","Edible Vegetable Oil (Palm Oil)","Iodised Salt","Wheat Gluten","Ragi Flour","Spices","Maltodextrin","Sugar","Flavor Enhancer (INS 627)","Flavor Enhancer (INS 631)","Dehydrated Vegetables"]},
  {id:"wai-wai-chicken",name:"Wai Wai Chicken Noodles",brand:"Wai Wai",category:"Instant Noodles",description:"Nepali-origin instant noodles popular in Northeast India.",weight:"75g",isVeg:false,ingredients:["Refined Wheat Flour (Maida)","Palm Oil","Iodised Salt","Chicken Seasoning Powder","Sugar","Maltodextrin","Flavor Enhancer (INS 621)","Flavor Enhancer (INS 627)","Flavor Enhancer (INS 631)","Garlic Powder","Spices","INS 150c"]},
  {id:"cup-noodles-mazedaar-masala",name:"Cup Noodles Mazedaar Masala",brand:"Nissin",category:"Instant Noodles",description:"Japanese cup noodles adapted for Indian palate.",weight:"70g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Palm Oil","Iodised Salt","Dehydrated Vegetables","Spices","Sugar","Maltodextrin","Flavor Enhancer (INS 621)","Flavor Enhancer (INS 627)","Flavor Enhancer (INS 631)","Acidity Regulator (INS 330)"]},
  {id:"ching-manchurian-noodles",name:"Manchurian Instant Noodles",brand:"Ching's Secret",category:"Instant Noodles",description:"Indo-Chinese Manchurian flavored noodles.",weight:"60g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Edible Vegetable Oil (Palmolein)","Salt","Wheat Gluten","Soy Sauce Powder","Maltodextrin","Sugar","Flavor Enhancer (INS 627)","Flavor Enhancer (INS 631)","Onion Powder","Garlic Powder","INS 150c"]},
  {id:"top-ramen-fiery-chilli",name:"Fiery Chilli Noodles",brand:"Top Ramen",category:"Instant Noodles",description:"Extra spicy instant noodles.",weight:"70g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Edible Vegetable Oil (Palmolein)","Iodised Salt","Wheat Gluten","Red Chilli Powder","Sugar","Maltodextrin","Flavor Enhancer (INS 627)","Flavor Enhancer (INS 631)","Acidity Regulator (INS 330)"]},
  // CHIPS & SNACKS (new)
  {id:"lays-chile-limon",name:"Chile Limon Chips",brand:"Lay's",category:"Chips & Snacks",description:"Tangy chili and lime flavored potato chips.",weight:"52g",isVeg:true,ingredients:["Potato","Edible Vegetable Oil (Palmolein, Rice Bran Oil)","Seasoning (Maltodextrin, Sugar, Iodised Salt, Spices, Chilli Powder, Lime Powder, Acidity Regulators (INS 330, INS 296), Anti-caking Agent (INS 551))"]},
  {id:"bingo-tedhe-medhe",name:"Tedhe Medhe Masala Tadka",brand:"Bingo",category:"Chips & Snacks",description:"Twisted corn puffs with masala seasoning.",weight:"66g",isVeg:true,ingredients:["Corn Grits","Edible Vegetable Oil (Palmolein)","Seasoning (Spices, Iodised Salt, Sugar, Maltodextrin, Tomato Powder, Onion Powder)","Acidity Regulator (INS 330)","Flavor Enhancer (INS 627)","Flavor Enhancer (INS 631)"]},
  {id:"kurkure-puffcorn-cheese",name:"Puffcorn Yummy Cheese",brand:"Kurkure",category:"Chips & Snacks",description:"Light and airy cheese-flavored corn puffs.",weight:"55g",isVeg:true,ingredients:["Corn Grits","Edible Vegetable Oil (Palmolein)","Seasoning (Cheese Powder, Maltodextrin, Iodised Salt, Sugar, Milk Solids, Spices)","Acidity Regulator (INS 330)","Anti-caking Agent (INS 551)","Color (INS 110)"]},
  {id:"balaji-wafers-masala",name:"Masala Wafers",brand:"Balaji",category:"Chips & Snacks",description:"Gujarat's favorite chip brand.",weight:"45g",isVeg:true,ingredients:["Potato","Edible Vegetable Oil (Palmolein)","Seasoning (Iodised Salt, Spices, Sugar, Maltodextrin, Tomato Powder, Chilli Powder)"]},
  {id:"diamond-banana-chips",name:"Banana Chips",brand:"Diamond",category:"Chips & Snacks",description:"Kerala-style banana chips fried in coconut oil.",weight:"180g",isVeg:true,ingredients:["Raw Banana","Coconut Oil","Iodised Salt","Turmeric"]},
  {id:"cornitos-nacho-crisps",name:"Nacho Crisps Cheese & Herbs",brand:"Cornitos",category:"Chips & Snacks",description:"Baked corn nacho chips with cheese and herb seasoning.",weight:"60g",isVeg:true,ingredients:["Corn Flour","Edible Vegetable Oil (Palmolein)","Seasoning (Cheese Powder, Maltodextrin, Iodised Salt, Herbs, Milk Solids, Sugar)","Acidity Regulator (INS 330)"]},
  {id:"pringles-sour-cream",name:"Sour Cream & Onion",brand:"Pringles",category:"Chips & Snacks",description:"Sour cream and onion flavored stackable crisps.",weight:"107g",isVeg:true,ingredients:["Dried Potatoes","Vegetable Oil (Sunflower, Corn)","Rice Flour","Wheat Starch","Maltodextrin","Salt","Sour Cream Powder","Onion Powder","Emulsifier (INS 471)","Dextrose","Sugar","Milk Solids"]},
  {id:"haldiram-all-in-one",name:"All In One Namkeen",brand:"Haldiram's",category:"Chips & Snacks",description:"Mixed snack with sev, peanuts, and flattened rice.",weight:"200g",isVeg:true,ingredients:["Gram Flour","Edible Vegetable Oil (Palmolein)","Peanuts","Flattened Rice","Iodised Salt","Spices","Sugar","Curry Leaves","INS 319 (TBHQ)"]},
  {id:"too-yumm-veggie-stix",name:"Veggie Stix Herbs & Spice",brand:"Too Yumm!",category:"Chips & Snacks",description:"Baked vegetable sticks marketed as healthy snacking.",weight:"45g",isVeg:true,ingredients:["Potato Flakes","Rice Flour","Edible Vegetable Oil (Rice Bran Oil)","Spinach Powder","Beetroot Powder","Seasoning (Salt, Sugar, Spices, Herbs, Maltodextrin)"]},
  // BISCUITS (new)
  {id:"britannia-50-50-maska",name:"50-50 Maska Chaska",brand:"Britannia",category:"Biscuits & Cookies",description:"Sweet and salty cracker biscuit with butter flavor.",weight:"62g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Edible Vegetable Oil (Palm Oil)","Sugar","Butter (3%)","Iodised Salt","Invert Syrup","Milk Solids","Raising Agents (INS 503(ii), INS 500(ii))","Emulsifier (INS 322)","Dough Conditioner (INS 223)","Artificial Flavoring - Butter"]},
  {id:"mcvities-digestive",name:"Digestive Biscuits",brand:"McVitie's",category:"Biscuits & Cookies",description:"Whole wheat digestive biscuits.",weight:"100g",isVeg:true,ingredients:["Whole Wheat Flour (Atta) (56%)","Sugar","Edible Vegetable Oil (Palm Oil)","Oat Flour","Raising Agents (INS 500(ii), INS 503(ii))","Iodised Salt","Emulsifier (INS 322)","Malt Extract"]},
  {id:"britannia-nutrichoice-oats",name:"NutriChoice Oats Cookies",brand:"Britannia",category:"Biscuits & Cookies",description:"Oats-based cookies.",weight:"75g",isVeg:true,ingredients:["Oat Flour (32%)","Refined Wheat Flour (Maida)","Sugar","Edible Vegetable Oil (Palm Oil)","Invert Syrup","Milk Solids","Raising Agents (INS 503(ii), INS 500(ii))","Iodised Salt","Emulsifier (INS 322)"]},
  {id:"unibic-choco-chip",name:"Choco Chip Cookies",brand:"Unibic",category:"Biscuits & Cookies",description:"Premium chocolate chip cookies.",weight:"75g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Sugar","Edible Vegetable Oil (Palm Oil)","Choco Chips (12%)","Cocoa Solids","Invert Syrup","Liquid Glucose","Butter","Milk Solids","Raising Agents (INS 500(ii), INS 503(ii))","Emulsifier (INS 322)","Iodised Salt"]},
  {id:"jim-jam-cream",name:"Jim Jam Cream Biscuit",brand:"Britannia",category:"Biscuits & Cookies",description:"Sandwich biscuit with fruit jam filling.",weight:"100g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Sugar","Edible Vegetable Fat (Palm Oil)","Mixed Fruit Jam (8%)","Invert Syrup","Liquid Glucose","Milk Solids","Raising Agents (INS 500(ii), INS 503(ii))","Emulsifier (INS 322)","Iodised Salt","Synthetic Color (INS 122)","Artificial Flavoring"]},
  {id:"parle-krackjack",name:"KrackJack Sweet & Salty",brand:"Parle",category:"Biscuits & Cookies",description:"Classic sweet and salty cracker biscuit.",weight:"75g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Edible Vegetable Oil (Palm Oil)","Sugar","Invert Syrup","Iodised Salt","Milk Solids","Raising Agents (INS 503(ii), INS 500(ii))","Emulsifier (INS 322)","Dough Conditioner (INS 223)"]},
  {id:"parle-20-20-butter",name:"20-20 Butter Cookies",brand:"Parle",category:"Biscuits & Cookies",description:"Affordable butter cookies from Parle.",weight:"75g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Sugar","Edible Vegetable Oil (Palm Oil)","Butter (5%)","Invert Syrup","Milk Solids","Raising Agents (INS 503(ii), INS 500(ii))","Iodised Salt","Emulsifier (INS 322)","Artificial Flavoring - Butter"]},
  {id:"oreo-chocolate-creme",name:"Oreo Chocolate Creme",brand:"Oreo",category:"Biscuits & Cookies",description:"Chocolate cream variant of the classic Oreo.",weight:"120g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Sugar","Edible Vegetable Fat (Palm Oil, Interesterified Vegetable Fat)","Cocoa Solids (8%)","Invert Sugar Syrup","Starch","Leavening Agents (INS 500(ii), INS 503(ii))","Iodised Salt","Emulsifier (INS 322)","Synthetic Food Color (INS 150d)","Artificial Flavoring"]},
  {id:"britannia-treat-croissant",name:"Treat Croissant Chocolate",brand:"Britannia",category:"Biscuits & Cookies",description:"Chocolate-filled croissant snack.",weight:"45g",isVeg:true,ingredients:["Refined Wheat Flour (Maida)","Sugar","Edible Vegetable Fat (Palm Oil, Interesterified Fat)","Chocolate Filling (Sugar, Cocoa Solids, Palm Oil, Emulsifier INS 322)","Invert Syrup","Yeast","Milk Solids","Iodised Salt","Emulsifier (INS 471)","Artificial Flavoring - Chocolate"]},
  // NAMKEEN (new)
  {id:"haldiram-khatta-meetha",name:"Khatta Meetha",brand:"Haldiram's",category:"Namkeen",description:"Sweet and tangy mixed namkeen.",weight:"200g",isVeg:true,ingredients:["Gram Flour","Edible Vegetable Oil (Palmolein)","Peanuts","Flattened Rice","Sugar","Iodised Salt","Spices","Dry Mango Powder","Maltodextrin","INS 319 (TBHQ)"]},
  {id:"haldiram-sev-bhujia",name:"Sev Bhujia",brand:"Haldiram's",category:"Namkeen",description:"Classic thin sev namkeen.",weight:"200g",isVeg:true,ingredients:["Gram Flour (Besan) (60%)","Edible Vegetable Oil (Palmolein)","Iodised Salt","Spices","Red Chilli","INS 319 (TBHQ)"]},
  {id:"bikano-aloo-bhujia",name:"Aloo Bhujia",brand:"Bikano",category:"Namkeen",description:"Bikano's version of the classic potato sev.",weight:"200g",isVeg:true,ingredients:["Potatoes (40%)","Edible Vegetable Oil (Palmolein)","Gram Flour","Iodised Salt","Spices","Starch","INS 319 (TBHQ)"]},
  {id:"haldiram-peanut-laddu",name:"Peanut Laddu",brand:"Haldiram's",category:"Namkeen",description:"Sweet peanut balls made with jaggery.",weight:"400g",isVeg:true,ingredients:["Peanuts (55%)","Jaggery","Sugar","Edible Vegetable Oil (Palmolein)","Cardamom"]},
  {id:"bikano-rasgulla",name:"Rasgulla",brand:"Bikano",category:"Namkeen",description:"Canned rasgulla in sugar syrup.",weight:"1kg",isVeg:true,ingredients:["Sugar","Water","Chhena (Milk Solids)","Preservative (INS 202)","Acidity Regulator (INS 330)"]},
];

async function main() {
  console.log('\n🌱 Adding extra products to Neon database...\n');
  
  // Get existing IDs
  const existing = await prisma.product.findMany({ select: { id: true } });
  const existingIds = new Set(existing.map(p => p.id));
  console.log(`📊 Currently ${existingIds.size} products in database`);
  
  let added = 0;
  let skipped = 0;
  
  for (const product of EXTRA_PRODUCTS) {
    if (existingIds.has(product.id)) {
      skipped++;
      continue;
    }
    const { score, redFlags } = scoreProduct(product.ingredients, product.category);
    try {
      await prisma.product.create({
        data: {
          id: product.id,
          name: product.name,
          brand: product.brand,
          category: product.category,
          description: product.description ?? null,
          weight: product.weight ?? null,
          isVeg: product.isVeg ?? null,
          ingredients: product.ingredients,
          imageUrl: null,
          transparencyScore: score,
          redFlags,
        },
      });
      added++;
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      if (!msg.includes('Unique constraint')) {
        console.warn(`  ⚠ Skipped ${product.id}: ${msg}`);
      }
      skipped++;
    }
  }
  
  const finalCount = await prisma.product.count();
  console.log(`\n✅ Added ${added} new products (skipped ${skipped} duplicates)`);
  console.log(`📊 Total products in database: ${finalCount}`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
